USE [TPM_Dev]
INSERT INTO [dbo].[Promo] ([Id], [Disabled], [DeletedDate], [BrandId], [TechnologyId], [PromoStatusId], [Name], [StartDate], [EndDate], [PlanPromoUpliftPercent], [ActualPromoUpliftPercent], [MarsMechanicId], [PlanInstoreMechanicId], [MarsMechanicDiscount], [PlanInstoreMechanicDiscount], [ClientHierarchy], [ProductHierarchy], [ClientTreeId])
VALUES (NEWID(), 0 ,NULL, (SELECT TOP 1 Id FROM Brand WHERE Name = 'Sheba'), (SELECT TOP 1 Id FROM Technology WHERE Name = 'Pouch'), (SELECT TOP 1 Id FROM PromoStatus WHERE SystemName = 'Closed'), 'TestUpliftPromo_06', '2017-06-05 00:00:00.0000000 +03:00', '2017-07-05 00:00:00.0000000 +03:00', 110, 100, (SELECT TOP 1 Id FROM Mechanic WHERE SystemName = 'TPR'), (SELECT TOP 1 Id FROM Mechanic WHERE SystemName = 'TPR'), 24, 24, 'NA > X5 Retail Group', 'SHEBA > Pouch > Pleasure;SHEBA > Pouch > Appetito;SHEBA > Pouch > Naturelle', (SELECT TOP 1 ObjectId FROM ClientTree WHERE Name = 'X5 Retail Group'))
INSERT INTO [dbo].[Promo] ([Id], [Disabled], [DeletedDate], [BrandId], [TechnologyId], [PromoStatusId], [Name], [StartDate], [EndDate], [PlanPromoUpliftPercent], [ActualPromoUpliftPercent], [MarsMechanicId], [PlanInstoreMechanicId], [MarsMechanicDiscount], [PlanInstoreMechanicDiscount], [ClientHierarchy], [ProductHierarchy], [ClientTreeId])
VALUES (NEWID(), 0 ,NULL, (SELECT TOP 1 Id FROM Brand WHERE Name = 'Sheba'), (SELECT TOP 1 Id FROM Technology WHERE Name = 'Pouch'), (SELECT TOP 1 Id FROM PromoStatus WHERE SystemName = 'Closed'), 'TestUpliftPromo_07', '2017-06-05 00:00:00.0000000 +03:00', '2017-07-05 00:00:00.0000000 +03:00', 115, 110, (SELECT TOP 1 Id FROM Mechanic WHERE SystemName = 'TPR'), (SELECT TOP 1 Id FROM Mechanic WHERE SystemName = 'TPR'), 24, 24, 'NA > X5 Retail Group', 'SHEBA > Pouch > Pleasure;SHEBA > Pouch > Appetito;SHEBA > Pouch > Naturelle', (SELECT TOP 1 ObjectId FROM ClientTree WHERE Name = 'X5 Retail Group'))
INSERT INTO [dbo].[Promo] ([Id], [Disabled], [DeletedDate], [BrandId], [TechnologyId], [PromoStatusId], [Name], [StartDate], [EndDate], [PlanPromoUpliftPercent], [ActualPromoUpliftPercent], [MarsMechanicId], [PlanInstoreMechanicId], [MarsMechanicDiscount], [PlanInstoreMechanicDiscount], [ClientHierarchy], [ProductHierarchy], [ClientTreeId])
VALUES (NEWID(), 0 ,NULL, (SELECT TOP 1 Id FROM Brand WHERE Name = 'Sheba'), (SELECT TOP 1 Id FROM Technology WHERE Name = 'Pouch'), (SELECT TOP 1 Id FROM PromoStatus WHERE SystemName = 'Closed'), 'TestUpliftPromo_08', '2017-06-05 00:00:00.0000000 +03:00', '2017-07-05 00:00:00.0000000 +03:00', 120, 120, (SELECT TOP 1 Id FROM Mechanic WHERE SystemName = 'TPR'), (SELECT TOP 1 Id FROM Mechanic WHERE SystemName = 'TPR'), 24, 24, 'NA > X5 Retail Group', 'SHEBA > Pouch > Pleasure;SHEBA > Pouch > Appetito;SHEBA > Pouch > Naturelle', (SELECT TOP 1 ObjectId FROM ClientTree WHERE Name = 'X5 Retail Group'))
INSERT INTO [dbo].[Promo] ([Id], [Disabled], [DeletedDate], [BrandId], [TechnologyId], [PromoStatusId], [Name], [StartDate], [EndDate], [PlanPromoUpliftPercent], [ActualPromoUpliftPercent], [MarsMechanicId], [PlanInstoreMechanicId], [MarsMechanicDiscount], [PlanInstoreMechanicDiscount], [ClientHierarchy], [ProductHierarchy], [ClientTreeId])
VALUES (NEWID(), 0 ,NULL, (SELECT TOP 1 Id FROM Brand WHERE Name = 'Sheba'), (SELECT TOP 1 Id FROM Technology WHERE Name = 'Pouch'), (SELECT TOP 1 Id FROM PromoStatus WHERE SystemName = 'Closed'), 'TestUpliftPromo_09', '2017-06-05 00:00:00.0000000 +03:00', '2017-07-05 00:00:00.0000000 +03:00', 120, 115, (SELECT TOP 1 Id FROM Mechanic WHERE SystemName = 'TPR'), (SELECT TOP 1 Id FROM Mechanic WHERE SystemName = 'TPR'), 24, 24, 'NA > X5 Retail Group', 'SHEBA > Pouch > Appetito', (SELECT TOP 1 ObjectId FROM ClientTree WHERE Name = 'X5 Retail Group'))
INSERT INTO [dbo].[Promo] ([Id], [Disabled], [DeletedDate], [BrandId], [TechnologyId], [PromoStatusId], [Name], [StartDate], [EndDate], [PlanPromoUpliftPercent], [ActualPromoUpliftPercent], [MarsMechanicId], [PlanInstoreMechanicId], [MarsMechanicDiscount], [PlanInstoreMechanicDiscount], [ClientHierarchy], [ProductHierarchy], [ClientTreeId])
VALUES (NEWID(), 0 ,NULL, (SELECT TOP 1 Id FROM Brand WHERE Name = 'Sheba'), (SELECT TOP 1 Id FROM Technology WHERE Name = 'Pouch'), (SELECT TOP 1 Id FROM PromoStatus WHERE SystemName = 'Closed'), 'TestUpliftPromo_10', '2017-06-05 00:00:00.0000000 +03:00', '2017-07-05 00:00:00.0000000 +03:00', 130, 80, (SELECT TOP 1 Id FROM Mechanic WHERE SystemName = 'TPR'), (SELECT TOP 1 Id FROM Mechanic WHERE SystemName = 'TPR'), 24, 24, 'NA > X5 Retail Group', 'SHEBA > Pouch > Naturelle', (SELECT TOP 1 ObjectId FROM ClientTree WHERE Name = 'X5 Retail Group'))

GO