USE [TPM_Dev]
GO

INSERT INTO [PromoSupportPromo]([Id],[Disabled],[DeletedDate],[PromoId],[PromoSupportId],[Calculation])
VALUES(NEWID(),0,NULL,(SELECT Id FROM Promo WHERE Name = 'TestUpliftPromo_01'),(SELECT TOP 1 Id FROM PromoSupport WHERE BudgetSubItemId = (SELECT Id FROM BudgetSubItem WHERE BudgetItemId = (SELECT Id FROM BudgetItem WHERE Name = 'Catalog'))),0)
INSERT INTO [PromoSupportPromo]([Id],[Disabled],[DeletedDate],[PromoId],[PromoSupportId],[Calculation])
VALUES(NEWID(),0,NULL,(SELECT Id FROM Promo WHERE Name = 'TestUpliftPromo_02'),(SELECT TOP 1 Id FROM PromoSupport WHERE BudgetSubItemId = (SELECT Id FROM BudgetSubItem WHERE BudgetItemId = (SELECT Id FROM BudgetItem WHERE Name = 'Catalog'))),0)
INSERT INTO [PromoSupportPromo]([Id],[Disabled],[DeletedDate],[PromoId],[PromoSupportId],[Calculation])
VALUES(NEWID(),0,NULL,(SELECT Id FROM Promo WHERE Name = 'TestUpliftPromo_03'),(SELECT TOP 1 Id FROM PromoSupport WHERE BudgetSubItemId = (SELECT Id FROM BudgetSubItem WHERE BudgetItemId = (SELECT Id FROM BudgetItem WHERE Name = 'Catalog'))),0)
INSERT INTO [PromoSupportPromo]([Id],[Disabled],[DeletedDate],[PromoId],[PromoSupportId],[Calculation])
VALUES(NEWID(),0,NULL,(SELECT Id FROM Promo WHERE Name = 'TestUpliftPromo_04'),(SELECT TOP 1 Id FROM PromoSupport WHERE BudgetSubItemId = (SELECT Id FROM BudgetSubItem WHERE BudgetItemId = (SELECT Id FROM BudgetItem WHERE Name = 'Catalog'))),0)
INSERT INTO [PromoSupportPromo]([Id],[Disabled],[DeletedDate],[PromoId],[PromoSupportId],[Calculation])
VALUES(NEWID(),0,NULL,(SELECT Id FROM Promo WHERE Name = 'TestUpliftPromo_05'),(SELECT TOP 1 Id FROM PromoSupport WHERE BudgetSubItemId = (SELECT Id FROM BudgetSubItem WHERE BudgetItemId = (SELECT Id FROM BudgetItem WHERE Name = 'Catalog'))),0)
INSERT INTO [PromoSupportPromo]([Id],[Disabled],[DeletedDate],[PromoId],[PromoSupportId],[Calculation])
VALUES(NEWID(),0,NULL,(SELECT Id FROM Promo WHERE Name = 'TestUpliftPromo_06'),(SELECT TOP 1 Id FROM PromoSupport WHERE BudgetSubItemId = (SELECT Id FROM BudgetSubItem WHERE BudgetItemId = (SELECT Id FROM BudgetItem WHERE Name = 'Catalog'))),0)
INSERT INTO [PromoSupportPromo]([Id],[Disabled],[DeletedDate],[PromoId],[PromoSupportId],[Calculation])
VALUES(NEWID(),0,NULL,(SELECT Id FROM Promo WHERE Name = 'TestUpliftPromo_07'),(SELECT TOP 1 Id FROM PromoSupport WHERE BudgetSubItemId = (SELECT Id FROM BudgetSubItem WHERE BudgetItemId = (SELECT Id FROM BudgetItem WHERE Name = 'Catalog'))),0)
INSERT INTO [PromoSupportPromo]([Id],[Disabled],[DeletedDate],[PromoId],[PromoSupportId],[Calculation])
VALUES(NEWID(),0,NULL,(SELECT Id FROM Promo WHERE Name = 'TestUpliftPromo_08'),(SELECT TOP 1 Id FROM PromoSupport WHERE BudgetSubItemId = (SELECT Id FROM BudgetSubItem WHERE BudgetItemId = (SELECT Id FROM BudgetItem WHERE Name = 'Catalog'))),0)
INSERT INTO [PromoSupportPromo]([Id],[Disabled],[DeletedDate],[PromoId],[PromoSupportId],[Calculation])
VALUES(NEWID(),0,NULL,(SELECT Id FROM Promo WHERE Name = 'TestUpliftPromo_09'),(SELECT TOP 1 Id FROM PromoSupport WHERE BudgetSubItemId = (SELECT Id FROM BudgetSubItem WHERE BudgetItemId = (SELECT Id FROM BudgetItem WHERE Name = 'Catalog'))),0)
INSERT INTO [PromoSupportPromo]([Id],[Disabled],[DeletedDate],[PromoId],[PromoSupportId],[Calculation])
VALUES(NEWID(),0,NULL,(SELECT Id FROM Promo WHERE Name = 'TestUpliftPromo_10'),(SELECT TOP 1 Id FROM PromoSupport WHERE BudgetSubItemId = (SELECT Id FROM BudgetSubItem WHERE BudgetItemId = (SELECT Id FROM BudgetItem WHERE Name = 'Catalog'))),0)

INSERT INTO [PromoSupportPromo]([Id],[Disabled],[DeletedDate],[PromoId],[PromoSupportId],[Calculation])
VALUES(NEWID(),0,NULL,(SELECT Id FROM Promo WHERE Name = 'TestUpliftPromo_01'),(SELECT TOP 1 Id FROM PromoSupport WHERE BudgetSubItemId = (SELECT TOP 1 Id FROM BudgetSubItem WHERE BudgetItemId = (SELECT TOP 1 Id FROM BudgetItem WHERE Name = 'X-sites'))),0)
INSERT INTO [PromoSupportPromo]([Id],[Disabled],[DeletedDate],[PromoId],[PromoSupportId],[Calculation])
VALUES(NEWID(),0,NULL,(SELECT Id FROM Promo WHERE Name = 'TestUpliftPromo_02'),(SELECT TOP 1 Id FROM PromoSupport WHERE BudgetSubItemId = (SELECT TOP 1 Id FROM BudgetSubItem WHERE BudgetItemId = (SELECT TOP 1 Id FROM BudgetItem WHERE Name = 'X-sites'))),0)
INSERT INTO [PromoSupportPromo]([Id],[Disabled],[DeletedDate],[PromoId],[PromoSupportId],[Calculation])									 														   
VALUES(NEWID(),0,NULL,(SELECT Id FROM Promo WHERE Name = 'TestUpliftPromo_03'),(SELECT TOP 1 Id FROM PromoSupport WHERE BudgetSubItemId = (SELECT TOP 1 Id FROM BudgetSubItem WHERE BudgetItemId = (SELECT TOP 1 Id FROM BudgetItem WHERE Name = 'X-sites'))),0)
INSERT INTO [PromoSupportPromo]([Id],[Disabled],[DeletedDate],[PromoId],[PromoSupportId],[Calculation])									  														  
VALUES(NEWID(),0,NULL,(SELECT Id FROM Promo WHERE Name = 'TestUpliftPromo_04'),(SELECT TOP 1 Id FROM PromoSupport WHERE BudgetSubItemId = (SELECT TOP 1 Id FROM BudgetSubItem WHERE BudgetItemId = (SELECT TOP 1 Id FROM BudgetItem WHERE Name = 'X-sites'))),0)
INSERT INTO [PromoSupportPromo]([Id],[Disabled],[DeletedDate],[PromoId],[PromoSupportId],[Calculation])									  														  
VALUES(NEWID(),0,NULL,(SELECT Id FROM Promo WHERE Name = 'TestUpliftPromo_05'),(SELECT TOP 1 Id FROM PromoSupport WHERE BudgetSubItemId = (SELECT TOP 1 Id FROM BudgetSubItem WHERE BudgetItemId = (SELECT TOP 1 Id FROM BudgetItem WHERE Name = 'X-sites'))),0)
INSERT INTO [PromoSupportPromo]([Id],[Disabled],[DeletedDate],[PromoId],[PromoSupportId],[Calculation])									  														   
VALUES(NEWID(),0,NULL,(SELECT Id FROM Promo WHERE Name = 'TestUpliftPromo_06'),(SELECT TOP 1 Id FROM PromoSupport WHERE BudgetSubItemId = (SELECT TOP 1 Id FROM BudgetSubItem WHERE BudgetItemId = (SELECT TOP 1 Id FROM BudgetItem WHERE Name = 'X-sites'))),0)
INSERT INTO [PromoSupportPromo]([Id],[Disabled],[DeletedDate],[PromoId],[PromoSupportId],[Calculation])									 														  
VALUES(NEWID(),0,NULL,(SELECT Id FROM Promo WHERE Name = 'TestUpliftPromo_07'),(SELECT TOP 1 Id FROM PromoSupport WHERE BudgetSubItemId = (SELECT TOP 1 Id FROM BudgetSubItem WHERE BudgetItemId = (SELECT TOP 1 Id FROM BudgetItem WHERE Name = 'X-sites'))),0)
INSERT INTO [PromoSupportPromo]([Id],[Disabled],[DeletedDate],[PromoId],[PromoSupportId],[Calculation])									  														  
VALUES(NEWID(),0,NULL,(SELECT Id FROM Promo WHERE Name = 'TestUpliftPromo_08'),(SELECT TOP 1 Id FROM PromoSupport WHERE BudgetSubItemId = (SELECT TOP 1 Id FROM BudgetSubItem WHERE BudgetItemId = (SELECT TOP 1 Id FROM BudgetItem WHERE Name = 'X-sites'))),0)
INSERT INTO [PromoSupportPromo]([Id],[Disabled],[DeletedDate],[PromoId],[PromoSupportId],[Calculation])									 														  
VALUES(NEWID(),0,NULL,(SELECT Id FROM Promo WHERE Name = 'TestUpliftPromo_09'),(SELECT TOP 1 Id FROM PromoSupport WHERE BudgetSubItemId = (SELECT TOP 1 Id FROM BudgetSubItem WHERE BudgetItemId = (SELECT TOP 1 Id FROM BudgetItem WHERE Name = 'X-sites'))),0)
INSERT INTO [PromoSupportPromo]([Id],[Disabled],[DeletedDate],[PromoId],[PromoSupportId],[Calculation])									  														   
VALUES(NEWID(),0,NULL,(SELECT Id FROM Promo WHERE Name = 'TestUpliftPromo_10'),(SELECT TOP 1 Id FROM PromoSupport WHERE BudgetSubItemId = (SELECT TOP 1 Id FROM BudgetSubItem WHERE BudgetItemId = (SELECT TOP 1 Id FROM BudgetItem WHERE Name = 'X-sites'))),0)

GO


