// <auto-generated />
namespace Module.Persist.TPM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class BrandTech_LinksBrandTechnology : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BrandTech_LinksBrandTechnology));
        
        string IMigrationMetadata.Id
        {
            get { return "201811220800097_BrandTech_LinksBrandTechnology"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
