namespace Module.Persist.TPM.Migrations
{
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class PromoFieldsRename : DbMigration
    {
        public override void Up()
        {
            RenameColumn(table: "dbo.Promo", name: "InstoreMechanicId", newName: "PlanInstoreMechanicId");
            RenameColumn(table: "dbo.Promo", name: "InstoreMechanicTypeId", newName: "PlanInstoreMechanicTypeId");
            RenameIndex(table: "dbo.Promo", name: "IX_InstoreMechanicId", newName: "IX_PlanInstoreMechanicId");
            RenameIndex(table: "dbo.Promo", name: "IX_InstoreMechanicTypeId", newName: "IX_PlanInstoreMechanicTypeId");
            AddColumn("dbo.Promo", "MechanicComment", c => c.String(maxLength: 255));
            AddColumn("dbo.Promo", "PlanInstoreMechanicDiscount", c => c.Int());
            AddColumn("dbo.Promo", "CalendarPriority", c => c.Int());
            AddColumn("dbo.Promo", "PlanPromoTIShopper", c => c.Int());
            AddColumn("dbo.Promo", "PlanPromoTIMarketing", c => c.Double());
            AddColumn("dbo.Promo", "PlanPromoBranding", c => c.Int());
            AddColumn("dbo.Promo", "PlanPromoCost", c => c.Int());
            AddColumn("dbo.Promo", "PlanPromoBTL", c => c.Int());
            AddColumn("dbo.Promo", "PlanPromoCostProduction", c => c.Double());
            AddColumn("dbo.Promo", "PlanPromoUpliftPercent", c => c.Double());
            AddColumn("dbo.Promo", "PlanPromoIncrementalLSV", c => c.Int());
            AddColumn("dbo.Promo", "PlanPromoLSV", c => c.Int());
            AddColumn("dbo.Promo", "PlanPromoROIPercent", c => c.Int());
            AddColumn("dbo.Promo", "PlanPromoIncrementalNSV", c => c.Int());
            AddColumn("dbo.Promo", "PlanPromoNetIncrementalNSV", c => c.Int());
            AddColumn("dbo.Promo", "PlanPromoIncrementalMAC", c => c.Int());
            AddColumn("dbo.Promo", "ActualPromoTIShopper", c => c.Int());
            AddColumn("dbo.Promo", "ActualPromoTIMarketing", c => c.Double());
            AddColumn("dbo.Promo", "ActualPromoBranding", c => c.Int());
            AddColumn("dbo.Promo", "ActualPromoBTL", c => c.Int());
            AddColumn("dbo.Promo", "ActualPromoCostProduction", c => c.Double());
            AddColumn("dbo.Promo", "ActualPromoCost", c => c.Int());
            AddColumn("dbo.Promo", "ActualPromoUpliftPercent", c => c.Double());
            AddColumn("dbo.Promo", "ActualPromoIncrementalLSV", c => c.Int());
            AddColumn("dbo.Promo", "ActualPromoLSV", c => c.Int());
            AddColumn("dbo.Promo", "ActualPromoROIPercent", c => c.Int());
            AddColumn("dbo.Promo", "ActualPromoIncrementalNSV", c => c.Int());
            AddColumn("dbo.Promo", "ActualPromoNetIncrementalNSV", c => c.Int());
            AddColumn("dbo.Promo", "ActualPromoIncrementalMAC", c => c.Int());
            AddColumn("dbo.PromoDemandChangeIncident", "OldPlanInstoreMechanic", c => c.String(maxLength: 20));
            AddColumn("dbo.PromoDemandChangeIncident", "NewPlanInstoreMechanic", c => c.String(maxLength: 20));
            AddColumn("dbo.PromoDemandChangeIncident", "OldPlanInstoreMechanicDiscount", c => c.Int());
            AddColumn("dbo.PromoDemandChangeIncident", "NewPlanInstoreMechanicDiscount", c => c.Int());
            AddColumn("dbo.PromoDemandChangeIncident", "OldPlanPromoUpliftPercent", c => c.Double());
            AddColumn("dbo.PromoDemandChangeIncident", "NewPlanPromoUpliftPercent", c => c.Double());
            AddColumn("dbo.PromoDemandChangeIncident", "OldPlanPromoIncrementalLSV", c => c.Int());
            AddColumn("dbo.PromoDemandChangeIncident", "NewPlanPromoIncrementalLSV", c => c.Int());
            DropColumn("dbo.Promo", "Comment");
            DropColumn("dbo.Promo", "InstoreMechanicDiscount");
            DropColumn("dbo.Promo", "Priority");
            DropColumn("dbo.Promo", "ShopperTi");
            DropColumn("dbo.Promo", "MarketingTi");
            DropColumn("dbo.Promo", "Branding");
            DropColumn("dbo.Promo", "TotalCost");
            DropColumn("dbo.Promo", "BTL");
            DropColumn("dbo.Promo", "CostProduction");
            DropColumn("dbo.Promo", "PlanUplift");
            DropColumn("dbo.Promo", "PlanIncrementalLsv");
            DropColumn("dbo.Promo", "PlanTotalPromoLsv");
            DropColumn("dbo.Promo", "PlanRoi");
            DropColumn("dbo.Promo", "PlanIncrementalNsv");
            DropColumn("dbo.Promo", "PlanTotalPromoNsv");
            DropColumn("dbo.Promo", "PlanIncrementalMac");
            DropColumn("dbo.Promo", "FactShopperTi");
            DropColumn("dbo.Promo", "FactMarketingTi");
            DropColumn("dbo.Promo", "FactBranding");
            DropColumn("dbo.Promo", "FactBTL");
            DropColumn("dbo.Promo", "FactCostProduction");
            DropColumn("dbo.Promo", "FactTotalCost");
            DropColumn("dbo.Promo", "FactUplift");
            DropColumn("dbo.Promo", "FactIncrementalLsv");
            DropColumn("dbo.Promo", "FactTotalPromoLsv");
            DropColumn("dbo.Promo", "FactRoi");
            DropColumn("dbo.Promo", "FactIncrementalNsv");
            DropColumn("dbo.Promo", "FactTotalPromoNsv");
            DropColumn("dbo.Promo", "FactIncrementalMac");
            DropColumn("dbo.PromoDemandChangeIncident", "OldMechanicInStore");
            DropColumn("dbo.PromoDemandChangeIncident", "NewMechanicInStore");
            DropColumn("dbo.PromoDemandChangeIncident", "OldInstoreMechanicDiscount");
            DropColumn("dbo.PromoDemandChangeIncident", "NewInstoreMechanicDiscount");
            DropColumn("dbo.PromoDemandChangeIncident", "OldPlanUplift");
            DropColumn("dbo.PromoDemandChangeIncident", "NewPlanUplift");
            DropColumn("dbo.PromoDemandChangeIncident", "OldPlanIncrementalLsv");
            DropColumn("dbo.PromoDemandChangeIncident", "NewPlanIncrementalLsv");
        }
        
        public override void Down()
        {
            AddColumn("dbo.PromoDemandChangeIncident", "NewPlanIncrementalLsv", c => c.Int());
            AddColumn("dbo.PromoDemandChangeIncident", "OldPlanIncrementalLsv", c => c.Int());
            AddColumn("dbo.PromoDemandChangeIncident", "NewPlanUplift", c => c.Double());
            AddColumn("dbo.PromoDemandChangeIncident", "OldPlanUplift", c => c.Double());
            AddColumn("dbo.PromoDemandChangeIncident", "NewInstoreMechanicDiscount", c => c.Int());
            AddColumn("dbo.PromoDemandChangeIncident", "OldInstoreMechanicDiscount", c => c.Int());
            AddColumn("dbo.PromoDemandChangeIncident", "NewMechanicInStore", c => c.String(maxLength: 20));
            AddColumn("dbo.PromoDemandChangeIncident", "OldMechanicInStore", c => c.String(maxLength: 20));
            AddColumn("dbo.Promo", "FactIncrementalMac", c => c.Int());
            AddColumn("dbo.Promo", "FactTotalPromoNsv", c => c.Int());
            AddColumn("dbo.Promo", "FactIncrementalNsv", c => c.Int());
            AddColumn("dbo.Promo", "FactRoi", c => c.Int());
            AddColumn("dbo.Promo", "FactTotalPromoLsv", c => c.Int());
            AddColumn("dbo.Promo", "FactIncrementalLsv", c => c.Int());
            AddColumn("dbo.Promo", "FactUplift", c => c.Double());
            AddColumn("dbo.Promo", "FactTotalCost", c => c.Int());
            AddColumn("dbo.Promo", "FactCostProduction", c => c.Double());
            AddColumn("dbo.Promo", "FactBTL", c => c.Int());
            AddColumn("dbo.Promo", "FactBranding", c => c.Int());
            AddColumn("dbo.Promo", "FactMarketingTi", c => c.Double());
            AddColumn("dbo.Promo", "FactShopperTi", c => c.Int());
            AddColumn("dbo.Promo", "PlanIncrementalMac", c => c.Int());
            AddColumn("dbo.Promo", "PlanTotalPromoNsv", c => c.Int());
            AddColumn("dbo.Promo", "PlanIncrementalNsv", c => c.Int());
            AddColumn("dbo.Promo", "PlanRoi", c => c.Int());
            AddColumn("dbo.Promo", "PlanTotalPromoLsv", c => c.Int());
            AddColumn("dbo.Promo", "PlanIncrementalLsv", c => c.Int());
            AddColumn("dbo.Promo", "PlanUplift", c => c.Double());
            AddColumn("dbo.Promo", "CostProduction", c => c.Double());
            AddColumn("dbo.Promo", "BTL", c => c.Int());
            AddColumn("dbo.Promo", "TotalCost", c => c.Int());
            AddColumn("dbo.Promo", "Branding", c => c.Int());
            AddColumn("dbo.Promo", "MarketingTi", c => c.Double());
            AddColumn("dbo.Promo", "ShopperTi", c => c.Int());
            AddColumn("dbo.Promo", "Priority", c => c.Int());
            AddColumn("dbo.Promo", "InstoreMechanicDiscount", c => c.Int());
            AddColumn("dbo.Promo", "Comment", c => c.String(maxLength: 255));
            DropColumn("dbo.PromoDemandChangeIncident", "NewPlanPromoIncrementalLSV");
            DropColumn("dbo.PromoDemandChangeIncident", "OldPlanPromoIncrementalLSV");
            DropColumn("dbo.PromoDemandChangeIncident", "NewPlanPromoUpliftPercent");
            DropColumn("dbo.PromoDemandChangeIncident", "OldPlanPromoUpliftPercent");
            DropColumn("dbo.PromoDemandChangeIncident", "NewPlanInstoreMechanicDiscount");
            DropColumn("dbo.PromoDemandChangeIncident", "OldPlanInstoreMechanicDiscount");
            DropColumn("dbo.PromoDemandChangeIncident", "NewPlanInstoreMechanic");
            DropColumn("dbo.PromoDemandChangeIncident", "OldPlanInstoreMechanic");
            DropColumn("dbo.Promo", "ActualPromoIncrementalMAC");
            DropColumn("dbo.Promo", "ActualPromoNetIncrementalNSV");
            DropColumn("dbo.Promo", "ActualPromoIncrementalNSV");
            DropColumn("dbo.Promo", "ActualPromoROIPercent");
            DropColumn("dbo.Promo", "ActualPromoLSV");
            DropColumn("dbo.Promo", "ActualPromoIncrementalLSV");
            DropColumn("dbo.Promo", "ActualPromoUpliftPercent");
            DropColumn("dbo.Promo", "ActualPromoCost");
            DropColumn("dbo.Promo", "ActualPromoCostProduction");
            DropColumn("dbo.Promo", "ActualPromoBTL");
            DropColumn("dbo.Promo", "ActualPromoBranding");
            DropColumn("dbo.Promo", "ActualPromoTIMarketing");
            DropColumn("dbo.Promo", "ActualPromoTIShopper");
            DropColumn("dbo.Promo", "PlanPromoIncrementalMAC");
            DropColumn("dbo.Promo", "PlanPromoNetIncrementalNSV");
            DropColumn("dbo.Promo", "PlanPromoIncrementalNSV");
            DropColumn("dbo.Promo", "PlanPromoROIPercent");
            DropColumn("dbo.Promo", "PlanPromoLSV");
            DropColumn("dbo.Promo", "PlanPromoIncrementalLSV");
            DropColumn("dbo.Promo", "PlanPromoUpliftPercent");
            DropColumn("dbo.Promo", "PlanPromoCostProduction");
            DropColumn("dbo.Promo", "PlanPromoBTL");
            DropColumn("dbo.Promo", "PlanPromoCost");
            DropColumn("dbo.Promo", "PlanPromoBranding");
            DropColumn("dbo.Promo", "PlanPromoTIMarketing");
            DropColumn("dbo.Promo", "PlanPromoTIShopper");
            DropColumn("dbo.Promo", "CalendarPriority");
            DropColumn("dbo.Promo", "PlanInstoreMechanicDiscount");
            DropColumn("dbo.Promo", "MechanicComment");
            RenameIndex(table: "dbo.Promo", name: "IX_PlanInstoreMechanicTypeId", newName: "IX_InstoreMechanicTypeId");
            RenameIndex(table: "dbo.Promo", name: "IX_PlanInstoreMechanicId", newName: "IX_InstoreMechanicId");
            RenameColumn(table: "dbo.Promo", name: "PlanInstoreMechanicTypeId", newName: "InstoreMechanicTypeId");
            RenameColumn(table: "dbo.Promo", name: "PlanInstoreMechanicId", newName: "InstoreMechanicId");
        }
    }
}
