// <auto-generated />
namespace Module.Persist.TPM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Promo_PromoProduct_PromoROIReport_ADD_RENAME_FIELDS : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Promo_PromoProduct_PromoROIReport_ADD_RENAME_FIELDS));
        
        string IMigrationMetadata.Id
        {
            get { return "201905311032521_Promo_PromoProduct_PromoROIReport_ADD_RENAME_FIELDS"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
