// <auto-generated />
namespace Module.Persist.TPM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class IncrementalReport_Change_To_Dispatches : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IncrementalReport_Change_To_Dispatches));
        
        string IMigrationMetadata.Id
        {
            get { return "201909101453035_IncrementalReport_Change_To_Dispatches"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
