// <auto-generated />
namespace Module.Persist.TPM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class TradeInvestmentsFields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(TradeInvestmentsFields));
        
        string IMigrationMetadata.Id
        {
            get { return "201904111303150_TradeInvestmentsFields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
