// <auto-generated />
namespace Module.Persist.TPM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Move_UserTimestamp_To_PromoSupport : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Move_UserTimestamp_To_PromoSupport));
        
        string IMigrationMetadata.Id
        {
            get { return "201903101204452_Move_UserTimestamp_To_PromoSupport"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
