// <auto-generated />
namespace Module.Persist.TPM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ProductChangeIncident_CREATE : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ProductChangeIncident_CREATE));
        
        string IMigrationMetadata.Id
        {
            get { return "201901211432260_ProductChangeIncident_CREATE"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
