// <auto-generated />
namespace Module.Persist.TPM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class NoneNego_ClientTreeIdProductTreeId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NoneNego_ClientTreeIdProductTreeId));
        
        string IMigrationMetadata.Id
        {
            get { return "201901090838332_NoneNego_ClientTreeIdProductTreeId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
