// <auto-generated />
namespace Module.Persist.TPM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Release_01_To_OtherTypesPromo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Release_01_To_OtherTypesPromo));
        
        string IMigrationMetadata.Id
        {
            get { return "201911220934598_Release_01_To_OtherTypesPromo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
