// <auto-generated />
namespace Module.Persist.TPM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class COGS_TI_Year_Remove_Attribute : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(COGS_TI_Year_Remove_Attribute));
        
        string IMigrationMetadata.Id
        {
            get { return "201911221514174_COGS_TI_Year_Remove_Attribute"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
