// <auto-generated />
namespace Module.Persist.TPM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Empty_migration_PromoFilteringOptimization : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Empty_migration_PromoFilteringOptimization));
        
        string IMigrationMetadata.Id
        {
            get { return "201911130723258_Empty_migration_PromoFilteringOptimization"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
