// <auto-generated />
namespace Module.Persist.TPM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Create_OPEN_ORDERS_BDM : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Create_OPEN_ORDERS_BDM));
        
        string IMigrationMetadata.Id
        {
            get { return "201910241457563_Create_OPEN_ORDERS_BDM"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
