// <auto-generated />
namespace Module.Persist.TPM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class NoneNego_ToDate_DeleteMaxValue : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(NoneNego_ToDate_DeleteMaxValue));
        
        string IMigrationMetadata.Id
        {
            get { return "201901231442007_NoneNego_ToDate_DeleteMaxValue"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
