// <auto-generated />
namespace Module.Persist.TPM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class IncrementalPromoReport_Split_By_Dispatches_FIX : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IncrementalPromoReport_Split_By_Dispatches_FIX));
        
        string IMigrationMetadata.Id
        {
            get { return "201909201018007_IncrementalPromoReport_Split_By_Dispatches_FIX"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
