// <auto-generated />
namespace Module.Persist.TPM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class BaseLine_Add_Product_And_ProductId_Fields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BaseLine_Add_Product_And_ProductId_Fields));
        
        string IMigrationMetadata.Id
        {
            get { return "201902190930231_BaseLine_Add_Product_And_ProductId_Fields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
