// <auto-generated />
namespace Module.Persist.TPM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Create_MARS_UNIVERSAL_PETCARE_CUSTOMERS_Table : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Create_MARS_UNIVERSAL_PETCARE_CUSTOMERS_Table));
        
        string IMigrationMetadata.Id
        {
            get { return "201910221710362_Create_MARS_UNIVERSAL_PETCARE_CUSTOMERS_Table"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
