// <auto-generated />
namespace Module.Persist.TPM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PostPromoEffect_Fields_Modification : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PostPromoEffect_Fields_Modification));
        
        string IMigrationMetadata.Id
        {
            get { return "201906161033594_PostPromoEffect_Fields_Modification"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
