// <auto-generated />
namespace Module.Persist.TPM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Chagne_XSites_Type_To_Double : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Chagne_XSites_Type_To_Double));
        
        string IMigrationMetadata.Id
        {
            get { return "201903211533175_Chagne_XSites_Type_To_Double"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
