// <auto-generated />
namespace Module.Persist.TPM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Promo_ChangeType_MarketingTI : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Promo_ChangeType_MarketingTI));
        
        string IMigrationMetadata.Id
        {
            get { return "201902121805410_Promo_ChangeType_MarketingTI"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
