// <auto-generated />
namespace Module.Persist.TPM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class ClientTreeBrandTech_IDeactivatable : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ClientTreeBrandTech_IDeactivatable));
        
        string IMigrationMetadata.Id
        {
            get { return "201910081751272_ClientTreeBrandTech_IDeactivatable"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
