// <auto-generated />
namespace Module.Persist.TPM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class EmptyIncremental2Appollo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EmptyIncremental2Appollo));
        
        string IMigrationMetadata.Id
        {
            get { return "202003161126077_EmptyIncremental2Appollo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
