// <auto-generated />
namespace Module.Persist.TPM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Remove_Drop_StartDate_andEndDate_From_MARS_UNIVERSAL_PETCARE_MATER : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Remove_Drop_StartDate_andEndDate_From_MARS_UNIVERSAL_PETCARE_MATER));
        
        string IMigrationMetadata.Id
        {
            get { return "202006090826557_Remove_Drop_StartDate_andEndDate_From_MARS_UNIVERSAL_PETCARE_MATER"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
