// <auto-generated />
namespace Module.Persist.TPM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Rename_BrandSegTechSub_In_MARS_UNIVERSAL_PETCARE_MATERIALS : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Rename_BrandSegTechSub_In_MARS_UNIVERSAL_PETCARE_MATERIALS));
        
        string IMigrationMetadata.Id
        {
            get { return "202006172249340_Rename_BrandSegTechSub_In_MARS_UNIVERSAL_PETCARE_MATERIALS"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
