// <auto-generated />
namespace Module.Persist.TPM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Change_discount_type_in_NoNego_from_int_to_double : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Change_discount_type_in_NoNego_from_int_to_double));
        
        string IMigrationMetadata.Id
        {
            get { return "202007061141147_Change_discount_type_in_NoNego_from_int_to_double"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
