// <auto-generated />
namespace Module.Persist.TPM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Insert_in_ServiceInfo_PROMO_NUMBERS_FOR_REAPPROVAL : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Insert_in_ServiceInfo_PROMO_NUMBERS_FOR_REAPPROVAL));
        
        string IMigrationMetadata.Id
        {
            get { return "202010011059290_Insert_in_ServiceInfo_PROMO_NUMBERS_FOR_REAPPROVAL"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
