// <auto-generated />
namespace Module.Persist.TPM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class EmptyMigrationIncremental2Apollo2 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(EmptyMigrationIncremental2Apollo2));
        
        string IMigrationMetadata.Id
        {
            get { return "202005191538104_EmptyMigrationIncremental2Apollo2"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
