// <auto-generated />
namespace Module.Persist.TPM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class IncrementalReport_View_Fixes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(IncrementalReport_View_Fixes));
        
        string IMigrationMetadata.Id
        {
            get { return "202004280800394_IncrementalReport_View_Fixes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
