// <auto-generated />
namespace Module.Persist.TPM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20200529_1427_Add_SubBrand_and_SubBrand_code_into_Technology : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20200529_1427_Add_SubBrand_and_SubBrand_code_into_Technology));
        
        string IMigrationMetadata.Id
        {
            get { return "202005291400077_20200529_1427_Add_SubBrand_and_SubBrand_code_into_Technology"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
