// <auto-generated />
namespace Module.Persist.TPM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PromoProductDifference_Fields_Mod_Qty : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PromoProductDifference_Fields_Mod_Qty));
        
        string IMigrationMetadata.Id
        {
            get { return "202004211315418_PromoProductDifference_Fields_Mod_Qty"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
