// <auto-generated />
namespace Module.Persist.TPM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _20200601_1402_Delete_unique_field_from_Tech_code_in_Technologies : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_20200601_1402_Delete_unique_field_from_Tech_code_in_Technologies));
        
        string IMigrationMetadata.Id
        {
            get { return "202006011234540_20200601_1402_Delete_unique_field_from_Tech_code_in_Technologies"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
