// <auto-generated />
namespace Module.Persist.TPM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class BTLPromo_Add_ClientTree_Field : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(BTLPromo_Add_ClientTree_Field));
        
        string IMigrationMetadata.Id
        {
            get { return "202003031138044_BTLPromo_Add_ClientTree_Field"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
