// <auto-generated />
namespace Module.Persist.TPM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Add_InvoiceTotal_and_InvoiceTotalProduct : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_InvoiceTotal_and_InvoiceTotalProduct));
        
        string IMigrationMetadata.Id
        {
            get { return "202003051626093_Add_InvoiceTotal_and_InvoiceTotalProduct"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
