// <auto-generated />
namespace Module.Persist.TPM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class MechanicType_ClientTreeId : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(MechanicType_ClientTreeId));
        
        string IMigrationMetadata.Id
        {
            get { return "202006091202321_MechanicType_ClientTreeId"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
