// <auto-generated />
namespace Module.Persist.TPM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class SuperReader_Drop_AP_LoopHandlers_Restart : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(SuperReader_Drop_AP_LoopHandlers_Restart));
        
        string IMigrationMetadata.Id
        {
            get { return "202010051527134_SuperReader_Drop_AP_LoopHandlers_Restart"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
