// <auto-generated />
namespace Module.Persist.TPM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Create_CalculateBaselineValues_Job : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Create_CalculateBaselineValues_Job));
        
        string IMigrationMetadata.Id
        {
            get { return "202003241412330_Create_CalculateBaselineValues_Job"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
