// <auto-generated />
namespace Module.Persist.TPM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class _202106301025001_Drop_Client : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(_202106301025001_Drop_Client));
        
        string IMigrationMetadata.Id
        {
            get { return "202106300726289_202106301025001_Drop_Client"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
