// <auto-generated />
namespace Module.Persist.TPM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Add_AddTIFields_To_ROIReportView : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_AddTIFields_To_ROIReportView));
        
        string IMigrationMetadata.Id
        {
            get { return "202102160812304_Add_AddTIFields_To_ROIReportView"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
