// <auto-generated />
namespace Module.Persist.TPM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Add_DescRu_To_Technology : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_DescRu_To_Technology));
        
        string IMigrationMetadata.Id
        {
            get { return "202103251057531_Add_DescRu_To_Technology"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
