// <auto-generated />
namespace Module.Persist.TPM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RPASetting_Update_Column_Type : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RPASetting_Update_Column_Type));
        
        string IMigrationMetadata.Id
        {
            get { return "202108021438374_RPASetting_Update_Column_Type"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
