// <auto-generated />
namespace Module.Persist.TPM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Anaplan_ClientDashboard_Modification : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Anaplan_ClientDashboard_Modification));
        
        string IMigrationMetadata.Id
        {
            get { return "202107192037591_Anaplan_ClientDashboard_Modification"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
