namespace Module.Persist.TPM.Migrations
{
    using System.Data.Entity.Migrations;
    using Core.Settings;
    
    public partial class Night_Recalculation_Temps_and_Procedures : DbMigration
    {
        public override void Up()
        {
            var defaultSchema = AppSettingsManager.GetSetting<string>("DefaultSchema", "dbo");
            SqlString = SqlString.Replace("DefaultSchemaSetting", defaultSchema);
            Sql(SqlString);
        }

        public override void Down()
        {
        }

        private string SqlString = @"
			ALTER   PROCEDURE [DefaultSchemaSetting].[AddNewPromoProduct]
				AS
				BEGIN
					DECLARE AddNewPromoProductCursor CURSOR FAST_FORWARD
					FOR 
					SELECT
						tpp.[DeletedDate],
						tpp.[ZREP],
						tpp.[PromoId],
						tpp.[ProductId],
						tpp.[EAN_Case],
						tpp.[PlanProductPCQty],
						tpp.[PlanProductPCLSV],
						tpp.[ActualProductPCQty],
						tpp.[ActualProductUOM],
						tpp.[ActualProductSellInPrice],
						tpp.[ActualProductShelfDiscount],
						tpp.[ActualProductPCLSV],
						tpp.[ActualProductUpliftPercent],
						tpp.[ActualProductIncrementalPCQty],
						tpp.[ActualProductIncrementalPCLSV],
						tpp.[ActualProductIncrementalLSV],
						tpp.[PlanProductUpliftPercent],
						tpp.[ActualProductLSV],
						tpp.[PlanProductBaselineLSV],
						tpp.[ActualProductPostPromoEffectQty],
						tpp.[PlanProductPostPromoEffectQty],
						tpp.[ProductEN],
						tpp.[PlanProductCaseQty],
						tpp.[PlanProductBaselineCaseQty],
						tpp.[ActualProductCaseQty],
						tpp.[PlanProductPostPromoEffectLSVW1],
						tpp.[PlanProductPostPromoEffectLSVW2],
						tpp.[PlanProductPostPromoEffectLSV],
						tpp.[ActualProductPostPromoEffectLSV],
						tpp.[PlanProductIncrementalCaseQty],
						tpp.[ActualProductPostPromoEffectQtyW1],
						tpp.[ActualProductPostPromoEffectQtyW2],
						tpp.[PlanProductPostPromoEffectQtyW1],
						tpp.[PlanProductPostPromoEffectQtyW2],
						tpp.[PlanProductPCPrice],
						tpp.[ActualProductBaselineLSV],
						tpp.[EAN_PC],
						tpp.[PlanProductCaseLSV],
						tpp.[ActualProductLSVByCompensation],
						tpp.[PlanProductLSV],
						tpp.[PlanProductIncrementalLSV],
						tpp.[AverageMarker],
						tpp.[Price],
						tpp.[SumInvoiceProduct],
						tpp.[ActualProductBaselineCaseQty],
						tpp.PlanProductBaselineVolume,
						tpp.PlanProductPostPromoEffectVolumeW1,
						tpp.PlanProductPostPromoEffectVolumeW2,
						tpp.PlanProductPostPromoEffectVolume,
						tpp.ActualProductQtySO
					FROM [DefaultSchemaSetting].[TEMP_PROMOPRODUCT] tpp;

					DECLARE 
						@DeletedDate datetimeoffset(7),
						@ZREP nvarchar(255),
						@PromoId uniqueidentifier,
						@ProductId uniqueidentifier,
						@EAN_Case nvarchar(255),
						@PlanProductPCQty int,
						@PlanProductPCLSV float,
						@ActualProductPCQty int,
						@ActualProductUOM nvarchar(max),
						@ActualProductSellInPrice float,
						@ActualProductShelfDiscount float,
						@ActualProductPCLSV float,
						@ActualProductUpliftPercent float,
						@ActualProductIncrementalPCQty float,
						@ActualProductIncrementalPCLSV float,
						@ActualProductIncrementalLSV float,
						@PlanProductUpliftPercent float,
						@ActualProductLSV float,
						@PlanProductBaselineLSV float,
						@ActualProductPostPromoEffectQty float,
						@PlanProductPostPromoEffectQty float,
						@ProductEN nvarchar(max),
						@PlanProductCaseQty float,
						@PlanProductBaselineCaseQty float,
						@ActualProductCaseQty float,
						@PlanProductPostPromoEffectLSVW1 float,
						@PlanProductPostPromoEffectLSVW2 float,
						@PlanProductPostPromoEffectLSV float,
						@ActualProductPostPromoEffectLSV float,
						@PlanProductIncrementalCaseQty float,
						@ActualProductPostPromoEffectQtyW1 float,
						@ActualProductPostPromoEffectQtyW2 float,
						@PlanProductPostPromoEffectQtyW1 float,
						@PlanProductPostPromoEffectQtyW2 float,
						@PlanProductPCPrice float,
						@ActualProductBaselineLSV float,
						@EAN_PC nvarchar(255),
						@PlanProductCaseLSV float,
						@ActualProductLSVByCompensation float,
						@PlanProductLSV float,
						@PlanProductIncrementalLSV float,
						@AverageMarker bit,
						@Price float,
						@SumInvoiceProduct float,
						@ActualProductBaselineCaseQty float,
						@PlanProductBaselineVolume float,
						@PlanProductPostPromoEffectVolumeW1 float,
						@PlanProductPostPromoEffectVolumeW2 float,
						@PlanProductPostPromoEffectVolume float,
						@ActualProductQtySO float;

					OPEN AddNewPromoProductCursor;
					WHILE 1 = 1
					BEGIN
						FETCH NEXT 
							FROM AddNewPromoProductCursor 
							INTO 
								@DeletedDate,
								@ZREP,
								@PromoId,
								@ProductId,
								@EAN_Case,
								@PlanProductPCQty,
								@PlanProductPCLSV,
								@ActualProductPCQty,
								@ActualProductUOM,
								@ActualProductSellInPrice,
								@ActualProductShelfDiscount,
								@ActualProductPCLSV,
								@ActualProductUpliftPercent,
								@ActualProductIncrementalPCQty,
								@ActualProductIncrementalPCLSV,
								@ActualProductIncrementalLSV,
								@PlanProductUpliftPercent,
								@ActualProductLSV,
								@PlanProductBaselineLSV,
								@ActualProductPostPromoEffectQty,
								@PlanProductPostPromoEffectQty,
								@ProductEN,
								@PlanProductCaseQty,
								@PlanProductBaselineCaseQty,
								@ActualProductCaseQty,
								@PlanProductPostPromoEffectLSVW1,
								@PlanProductPostPromoEffectLSVW2,
								@PlanProductPostPromoEffectLSV,
								@ActualProductPostPromoEffectLSV,
								@PlanProductIncrementalCaseQty,
								@ActualProductPostPromoEffectQtyW1,
								@ActualProductPostPromoEffectQtyW2,
								@PlanProductPostPromoEffectQtyW1,
								@PlanProductPostPromoEffectQtyW2,
								@PlanProductPCPrice,
								@ActualProductBaselineLSV,
								@EAN_PC,
								@PlanProductCaseLSV,
								@ActualProductLSVByCompensation,
								@PlanProductLSV,
								@PlanProductIncrementalLSV,
								@AverageMarker,
								@Price,
								@SumInvoiceProduct,
								@ActualProductBaselineCaseQty,
								@PlanProductBaselineVolume,
								@PlanProductPostPromoEffectVolumeW1,
								@PlanProductPostPromoEffectVolumeW2,
								@PlanProductPostPromoEffectVolume,
								@ActualProductQtySO;

						IF (SELECT FETCH_STATUS FROM SYS.DM_EXEC_CURSORS(0) WHERE NAME = 'AddNewPromoProductCursor') <> 0
							BREAK;
				
						INSERT INTO [DefaultSchemaSetting].[PromoProduct]
								VALUES (
									NEWID(),
									0,
									@DeletedDate,
									@ZREP,
									@PromoId,
									@ProductId,
									@EAN_Case,
									@PlanProductPCQty,
									@PlanProductPCLSV,
									@ActualProductPCQty,
									@ActualProductUOM,
									@ActualProductSellInPrice,
									@ActualProductShelfDiscount,
									@ActualProductPCLSV,
									@ActualProductUpliftPercent,
									@ActualProductIncrementalPCQty,
									@ActualProductIncrementalPCLSV,
									@ActualProductIncrementalLSV,
									@PlanProductUpliftPercent,
									@ActualProductLSV,
									@PlanProductBaselineLSV,
									@ActualProductPostPromoEffectQty,
									@PlanProductPostPromoEffectQty,
									@ProductEN,
									@PlanProductCaseQty,
									@PlanProductBaselineCaseQty,
									@ActualProductCaseQty,
									@PlanProductPostPromoEffectLSVW1,
									@PlanProductPostPromoEffectLSVW2,
									@PlanProductPostPromoEffectLSV,
									@ActualProductPostPromoEffectLSV,
									@PlanProductIncrementalCaseQty,
									@ActualProductPostPromoEffectQtyW1,
									@ActualProductPostPromoEffectQtyW2,
									@PlanProductPostPromoEffectQtyW1,
									@PlanProductPostPromoEffectQtyW2,
									@PlanProductPCPrice,
									@ActualProductBaselineLSV,
									@EAN_PC,
									@PlanProductCaseLSV,
									@ActualProductLSVByCompensation,
									@PlanProductLSV,
									@PlanProductIncrementalLSV,
									@AverageMarker,
									@Price,
									@SumInvoiceProduct,
									@ActualProductBaselineCaseQty,
									NULL,
									@PlanProductBaselineVolume,
									@PlanProductPostPromoEffectVolumeW1,
									@PlanProductPostPromoEffectVolumeW2,
									@PlanProductPostPromoEffectVolume,
									@ActualProductQtySO
								);
							END;
					CLOSE AddNewPromoProductCursor;
					DEALLOCATE AddNewPromoProductCursor;
				END;
	GO
			
			ALTER   PROCEDURE [DefaultSchemaSetting].[UpdatePromo]
				AS
				BEGIN
					UPDATE [DefaultSchemaSetting].[Promo]
					SET
						[Disabled] = tp.[Disabled],
						[DeletedDate] = tp.[DeletedDate],
						[BrandId] = tp.[BrandId],
						[BrandTechId] = tp.[BrandTechId],
						[PromoStatusId] = tp.[PromoStatusId],
						[Name] = tp.[Name],
						[StartDate] = TODATETIMEOFFSET ( tp.[StartDate] , '+03:00' ),
						[EndDate] = TODATETIMEOFFSET ( tp.[EndDate] , '+03:00' ),
						[DispatchesStart] = TODATETIMEOFFSET ( tp.[DispatchesStart] , '+03:00' ),
						[DispatchesEnd] = TODATETIMEOFFSET ( tp.[DispatchesEnd] , '+03:00' ),
						[ColorId] = tp.[ColorId],
						[Number] = tp.[Number],
						[RejectReasonId] = tp.[RejectReasonId],
						[EventId] = tp.[EventId],
						[MarsMechanicId] = tp.[MarsMechanicId],
						[MarsMechanicTypeId] = tp.[MarsMechanicTypeId],
						[PlanInstoreMechanicId] = tp.[PlanInstoreMechanicId],
						[PlanInstoreMechanicTypeId] = tp.[PlanInstoreMechanicTypeId],
						[MarsMechanicDiscount] = tp.[MarsMechanicDiscount],
						[OtherEventName] = tp.[OtherEventName],
						[EventName] = tp.[EventName],
						[ClientHierarchy] = tp.[ClientHierarchy],
						[ProductHierarchy] = tp.[ProductHierarchy],
						[CreatorId] = tp.[CreatorId],
						[MarsStartDate] = tp.[MarsStartDate],
						[MarsEndDate] = tp.[MarsEndDate],
						[MarsDispatchesStart] = tp.[MarsDispatchesStart],
						[MarsDispatchesEnd] = tp.[MarsDispatchesEnd],
						[ClientTreeId] = tp.[ClientTreeId],
						[BaseClientTreeId] = tp.[BaseClientTreeId],
						[Mechanic] = tp.[Mechanic],
						[MechanicIA] = tp.[MechanicIA],
						[BaseClientTreeIds] = tp.[BaseClientTreeIds],
						[LastApprovedDate] = TODATETIMEOFFSET ( tp.[LastApprovedDate] , '+03:00' ),
						[TechnologyId] = tp.[TechnologyId],
						[NeedRecountUplift] = tp.[NeedRecountUplift],
						[IsAutomaticallyApproved] = tp.[IsAutomaticallyApproved],
						[IsCMManagerApproved] = tp.[IsCMManagerApproved],
						[IsDemandPlanningApproved] = tp.[IsDemandPlanningApproved],
						[IsDemandFinanceApproved] = tp.[IsDemandFinanceApproved],
						[PlanPromoXSites] = tp.[PlanPromoXSites],
						[PlanPromoCatalogue] = tp.[PlanPromoCatalogue],
						[PlanPromoPOSMInClient] = tp.[PlanPromoPOSMInClient],
						[PlanPromoCostProdXSites] = tp.[PlanPromoCostProdXSites],
						[PlanPromoCostProdCatalogue] = tp.[PlanPromoCostProdCatalogue],
						[PlanPromoCostProdPOSMInClient] = tp.[PlanPromoCostProdPOSMInClient],
						[ActualPromoXSites] = tp.[ActualPromoXSites],
						[ActualPromoCatalogue] = tp.[ActualPromoCatalogue],
						[ActualPromoPOSMInClient] = tp.[ActualPromoPOSMInClient],
						[ActualPromoCostProdXSites] = tp.[ActualPromoCostProdXSites],
						[ActualPromoCostProdCatalogue] = tp.[ActualPromoCostProdCatalogue],
						[ActualPromoCostProdPOSMInClient] = tp.[ActualPromoCostProdPOSMInClient],
						[MechanicComment] = tp.[MechanicComment],
						[PlanInstoreMechanicDiscount] = tp.[PlanInstoreMechanicDiscount],
						[CalendarPriority] = tp.[CalendarPriority],
						[PlanPromoTIShopper] = tp.[PlanPromoTIShopper],
						[PlanPromoTIMarketing] = tp.[PlanPromoTIMarketing],
						[PlanPromoBranding] = tp.[PlanPromoBranding],
						[PlanPromoCost] = tp.[PlanPromoCost],
						[PlanPromoBTL] = tp.[PlanPromoBTL],
						[PlanPromoCostProduction] = tp.[PlanPromoCostProduction],
						[PlanPromoUpliftPercent] = tp.[PlanPromoUpliftPercent],
						[PlanPromoIncrementalLSV] = tp.[PlanPromoIncrementalLSV],
						[PlanPromoLSV] = tp.[PlanPromoLSV],
						[PlanPromoROIPercent] = tp.[PlanPromoROIPercent],
						[PlanPromoIncrementalNSV] = tp.[PlanPromoIncrementalNSV],
						[PlanPromoNetIncrementalNSV] = tp.[PlanPromoNetIncrementalNSV],
						[PlanPromoIncrementalMAC] = tp.[PlanPromoIncrementalMAC],
						[ActualPromoTIShopper] = tp.[ActualPromoTIShopper],
						[ActualPromoTIMarketing] = tp.[ActualPromoTIMarketing],
						[ActualPromoBranding] = tp.[ActualPromoBranding],
						[ActualPromoBTL] = tp.[ActualPromoBTL],
						[ActualPromoCostProduction] = tp.[ActualPromoCostProduction],
						[ActualPromoCost] = tp.[ActualPromoCost],
						[ActualPromoUpliftPercent] = tp.[ActualPromoUpliftPercent],
						[ActualPromoIncrementalLSV] = tp.[ActualPromoIncrementalLSV],
						[ActualPromoLSV] = tp.[ActualPromoLSV],
						[ActualPromoROIPercent] = tp.[ActualPromoROIPercent],
						[ActualPromoIncrementalNSV] = tp.[ActualPromoIncrementalNSV],
						[ActualPromoNetIncrementalNSV] = tp.[ActualPromoNetIncrementalNSV],
						[ActualPromoIncrementalMAC] = tp.[ActualPromoIncrementalMAC],
						[ActualInStoreMechanicId] = tp.[ActualInStoreMechanicId],
						[ActualInStoreMechanicTypeId] = tp.[ActualInStoreMechanicTypeId],
						[PromoDuration] = tp.[PromoDuration],
						[DispatchDuration] = tp.[DispatchDuration],
						[InvoiceNumber] = tp.[InvoiceNumber],
						[PlanPromoBaselineLSV] = tp.[PlanPromoBaselineLSV],
						[PlanPromoIncrementalBaseTI] = tp.[PlanPromoIncrementalBaseTI],
						[PlanPromoIncrementalCOGS] = tp.[PlanPromoIncrementalCOGS],
						[PlanPromoTotalCost] = tp.[PlanPromoTotalCost],
						[PlanPromoNetIncrementalLSV] = tp.[PlanPromoNetIncrementalLSV],
						[PlanPromoNetLSV] = tp.[PlanPromoNetLSV],
						[PlanPromoNetIncrementalMAC] = tp.[PlanPromoNetIncrementalMAC],
						[PlanPromoIncrementalEarnings] = tp.[PlanPromoIncrementalEarnings],
						[PlanPromoNetIncrementalEarnings] = tp.[PlanPromoNetIncrementalEarnings],
						[PlanPromoNetROIPercent] = tp.[PlanPromoNetROIPercent],
						[PlanPromoNetUpliftPercent] = tp.[PlanPromoNetUpliftPercent],
						[ActualPromoBaselineLSV] = tp.[ActualPromoBaselineLSV],
						[ActualInStoreDiscount] = tp.[ActualInStoreDiscount],
						[ActualInStoreShelfPrice] = tp.[ActualInStoreShelfPrice],
						[ActualPromoIncrementalBaseTI] = tp.[ActualPromoIncrementalBaseTI],
						[ActualPromoIncrementalCOGS] = tp.[ActualPromoIncrementalCOGS],
						[ActualPromoTotalCost] = tp.[ActualPromoTotalCost],
						[ActualPromoNetIncrementalLSV] = tp.[ActualPromoNetIncrementalLSV],
						[ActualPromoNetLSV] = tp.[ActualPromoNetLSV],
						[ActualPromoNetIncrementalMAC] = tp.[ActualPromoNetIncrementalMAC],
						[ActualPromoIncrementalEarnings] = tp.[ActualPromoIncrementalEarnings],
						[ActualPromoNetIncrementalEarnings] = tp.[ActualPromoNetIncrementalEarnings],
						[ActualPromoNetROIPercent] = tp.[ActualPromoNetROIPercent],
						[ActualPromoNetUpliftPercent] = tp.[ActualPromoNetUpliftPercent],
						[Calculating] = tp.[Calculating],
						[BlockInformation] = tp.[BlockInformation],
						[PlanPromoBaselineBaseTI] = tp.[PlanPromoBaselineBaseTI],
						[PlanPromoBaseTI] = tp.[PlanPromoBaseTI],
						[PlanPromoNetNSV] = tp.[PlanPromoNetNSV],
						[ActualPromoBaselineBaseTI] = tp.[ActualPromoBaselineBaseTI],
						[ActualPromoBaseTI] = tp.[ActualPromoBaseTI],
						[ActualPromoNetNSV] = tp.[ActualPromoNetNSV],
						[ProductSubrangesList] = tp.[ProductSubrangesList],
						[ClientTreeKeyId] = tp.[ClientTreeKeyId],
						[InOut] = tp.[InOut],
						[PlanPromoNetIncrementalBaseTI] = tp.[PlanPromoNetIncrementalBaseTI],
						[PlanPromoNetIncrementalCOGS] = tp.[PlanPromoNetIncrementalCOGS],
						[ActualPromoNetIncrementalBaseTI] = tp.[ActualPromoNetIncrementalBaseTI],
						[ActualPromoNetIncrementalCOGS] = tp.[ActualPromoNetIncrementalCOGS],
						[PlanPromoNetBaseTI] = tp.[PlanPromoNetBaseTI],
						[PlanPromoNSV] = tp.[PlanPromoNSV],
						[ActualPromoNetBaseTI] = tp.[ActualPromoNetBaseTI],
						[ActualPromoNSV] = tp.[ActualPromoNSV],
						[ActualPromoLSVByCompensation] = tp.[ActualPromoLSVByCompensation],
						[PlanInStoreShelfPrice] = tp.[PlanInStoreShelfPrice],
						[PlanPromoPostPromoEffectLSVW1] = tp.[PlanPromoPostPromoEffectLSVW1],
						[PlanPromoPostPromoEffectLSVW2] = tp.[PlanPromoPostPromoEffectLSVW2],
						[PlanPromoPostPromoEffectLSV] = tp.[PlanPromoPostPromoEffectLSV],
						[ActualPromoPostPromoEffectLSVW1] = tp.[ActualPromoPostPromoEffectLSVW1],
						[ActualPromoPostPromoEffectLSVW2] = tp.[ActualPromoPostPromoEffectLSVW2],
						[ActualPromoPostPromoEffectLSV] = tp.[ActualPromoPostPromoEffectLSV],
						[LoadFromTLC] = tp.[LoadFromTLC],
						[InOutProductIds] = tp.[InOutProductIds],
						[InOutExcludeAssortmentMatrixProductsButtonPressed] = tp.[InOutExcludeAssortmentMatrixProductsButtonPressed],
						[DocumentNumber] = tp.[DocumentNumber],
						[LastChangedDate] = TODATETIMEOFFSET ( tp.[LastChangedDate] , '+03:00' ),
						[LastChangedDateDemand] = TODATETIMEOFFSET ( tp.[LastChangedDateDemand] , '+03:00' ),
						[LastChangedDateFinance] = TODATETIMEOFFSET ( tp.[LastChangedDateFinance] , '+03:00' ),
						[RegularExcludedProductIds] = tp.[RegularExcludedProductIds],
						[AdditionalUserTimestamp] = tp.[AdditionalUserTimestamp],
						[IsGrowthAcceleration] = tp.[IsGrowthAcceleration],
						[PromoTypesId] = tp.[PromoTypesId],
						[CreatorLogin] = tp.[CreatorLogin],
						[PlanTIBasePercent] = tp.[PlanTIBasePercent],
						[PlanCOGSPercent] = tp.[PlanCOGSPercent],
						[ActualTIBasePercent] = tp.[ActualTIBasePercent],
						[ActualCOGSPercent] = tp.[ActualCOGSPercent],
						[SumInvoice] = tp.[SumInvoice],
						[IsOnInvoice] = tp.[IsOnInvoice],
						[ActualPromoLSVSI] = tp.[ActualPromoLSVSI],
						[ActualPromoLSVSO] = tp.[ActualPromoLSVSO],
						[IsApolloExport] = tp.[IsApolloExport],
						[DeviationCoefficient] = tp.[DeviationCoefficient],
						[UseActualTI] = tp.[UseActualTI],
						[UseActualCOGS] = tp.[UseActualCOGS],
						[BudgetYear] = tp.[BudgetYear],
						[PlanAddTIShopperApproved] = tp.[PlanAddTIShopperApproved],
						[PlanAddTIShopperCalculated] = tp.[PlanAddTIShopperCalculated],
						[PlanAddTIMarketingApproved] = tp.[PlanAddTIMarketingApproved],
						[ActualAddTIShopper] = tp.[ActualAddTIShopper],
						[ActualAddTIMarketing] = tp.[ActualAddTIMarketing],
						[PlanPromoBaselineVolume] = tp.[PlanPromoBaselineVolume],
						[PlanPromoPostPromoEffectVolume] = tp.[PlanPromoPostPromoEffectVolume],
						[PlanPromoPostPromoEffectVolumeW1] = tp.[PlanPromoPostPromoEffectVolumeW1],
						[PlanPromoPostPromoEffectVolumeW2] = tp.[PlanPromoPostPromoEffectVolumeW2],
						[PlanPromoIncrementalVolume] = tp.[PlanPromoIncrementalVolume],
						[PlanPromoNetIncrementalVolume] = tp.[PlanPromoNetIncrementalVolume],
						[ActualPromoBaselineVolume] = tp.[ActualPromoBaselineVolume],
						[ActualPromoPostPromoEffectVolume] = tp.[ActualPromoPostPromoEffectVolume],
						[ActualPromoVolumeByCompensation] = tp.[ActualPromoVolumeByCompensation],
						[ActualPromoVolumeSI] = tp.[ActualPromoVolumeSI],
						[ActualPromoVolume] = tp.[ActualPromoVolume],
						[ActualPromoIncrementalVolume] = tp.[ActualPromoIncrementalVolume],
						[ActualPromoNetIncrementalVolume] = tp.[ActualPromoNetIncrementalVolume],
						[PlanPromoIncrementalCOGSTn] = tp.[PlanPromoIncrementalCOGSTn],
						[PlanPromoNetIncrementalCOGSTn] = tp.[PlanPromoNetIncrementalCOGSTn],
						[ActualPromoIncrementalCOGSTn] = tp.[ActualPromoIncrementalCOGSTn],
						[ActualPromoNetIncrementalCOGSTn] = tp.[ActualPromoNetIncrementalCOGSTn],
						[IsLSVBased] = tp.[IsLSVBased],
						[PlanPromoIncrementalMACLSV] = tp.[PlanPromoIncrementalMACLSV],
						[PlanPromoNetIncrementalMACLSV] = tp.[PlanPromoNetIncrementalMACLSV],
						[ActualPromoIncrementalMACLSV] = tp.[ActualPromoIncrementalMACLSV],
						[ActualPromoNetIncrementalMACLSV] = tp.[ActualPromoNetIncrementalMACLSV],
						[PlanPromoIncrementalEarningsLSV] = tp.[PlanPromoIncrementalEarningsLSV],
						[PlanPromoNetIncrementalEarningsLSV] = tp.[PlanPromoNetIncrementalEarningsLSV],
						[ActualPromoIncrementalEarningsLSV] = tp.[ActualPromoIncrementalEarningsLSV],
						[ActualPromoNetIncrementalEarningsLSV] = tp.[ActualPromoNetIncrementalEarningsLSV],
						[PlanPromoROIPercentLSV] = tp.[PlanPromoROIPercentLSV],
						[PlanPromoNetROIPercentLSV] = tp.[PlanPromoNetROIPercentLSV],
						[ActualPromoROIPercentLSV] = tp.[ActualPromoROIPercentLSV],
						[ActualPromoNetROIPercentLSV] = tp.[ActualPromoNetROIPercentLSV],
						[PlanCOGSTn] = tp.[PlanCOGSTn],
						[ActualCOGSTn] = tp.[ActualCOGSTn]
					FROM
						(SELECT * FROM [DefaultSchemaSetting].[TEMP_PROMO]) AS tp WHERE [DefaultSchemaSetting].[Promo].[Id] = tp.Id
			
					UPDATE [DefaultSchemaSetting].[PromoProduct]
					SET
						[Disabled] = tpp.[Disabled],
						[DeletedDate] = tpp.[DeletedDate],
						[ZREP] = tpp.[ZREP],
						[PromoId] = tpp.[PromoId],
						[ProductId] = tpp.[ProductId],
						[EAN_Case] = tpp.[EAN_Case],
						[PlanProductPCQty] = TRY_CAST(tpp.[PlanProductPCQty] AS INT),
						[PlanProductPCLSV] = tpp.[PlanProductPCLSV],
						[ActualProductPCQty] = TRY_CAST(tpp.[ActualProductPCQty] AS INT),
						[ActualProductUOM] = tpp.[ActualProductUOM],
						[ActualProductSellInPrice] = tpp.[ActualProductSellInPrice],
						[ActualProductShelfDiscount] = tpp.[ActualProductShelfDiscount],
						[ActualProductPCLSV] = tpp.[ActualProductPCLSV],
						[ActualProductUpliftPercent] = tpp.[ActualProductUpliftPercent],
						[ActualProductIncrementalPCQty] = tpp.[ActualProductIncrementalPCQty],
						[ActualProductIncrementalPCLSV] = tpp.[ActualProductIncrementalPCLSV],
						[ActualProductIncrementalLSV] = tpp.[ActualProductIncrementalLSV],
						[PlanProductUpliftPercent] = tpp.[PlanProductUpliftPercent],
						[ActualProductLSV] = tpp.[ActualProductLSV],
						[PlanProductBaselineLSV] = tpp.[PlanProductBaselineLSV],
						[ActualProductPostPromoEffectQty] = tpp.[ActualProductPostPromoEffectQty],
						[PlanProductPostPromoEffectQty] = tpp.[PlanProductPostPromoEffectQty],
						[ProductEN] = tpp.[ProductEN],
						[PlanProductCaseQty] = tpp.[PlanProductCaseQty],
						[PlanProductBaselineCaseQty] = tpp.[PlanProductBaselineCaseQty],
						[ActualProductCaseQty] = tpp.[ActualProductCaseQty],
						[PlanProductPostPromoEffectLSVW1] = tpp.[PlanProductPostPromoEffectLSVW1],
						[PlanProductPostPromoEffectLSVW2] = tpp.[PlanProductPostPromoEffectLSVW2],
						[PlanProductPostPromoEffectLSV] = tpp.[PlanProductPostPromoEffectLSV],
						[ActualProductPostPromoEffectLSV] = tpp.[ActualProductPostPromoEffectLSV],
						[PlanProductIncrementalCaseQty] = tpp.[PlanProductIncrementalCaseQty],
						[ActualProductPostPromoEffectQtyW1] = tpp.[ActualProductPostPromoEffectQtyW1],
						[ActualProductPostPromoEffectQtyW2] = tpp.[ActualProductPostPromoEffectQtyW2],
						[PlanProductPostPromoEffectQtyW1] = tpp.[PlanProductPostPromoEffectQtyW1],
						[PlanProductPostPromoEffectQtyW2] = tpp.[PlanProductPostPromoEffectQtyW2],
						[PlanProductPCPrice] = tpp.[PlanProductPCPrice],
						[ActualProductBaselineLSV] = tpp.[ActualProductBaselineLSV],
						[EAN_PC] = tpp.[EAN_PC],
						[PlanProductCaseLSV] = tpp.[PlanProductCaseLSV],
						[ActualProductLSVByCompensation] = tpp.[ActualProductLSVByCompensation],
						[PlanProductLSV] = tpp.[PlanProductLSV],
						[PlanProductIncrementalLSV] = tpp.[PlanProductIncrementalLSV],
						[AverageMarker] = tpp.[AverageMarker],
						[Price] = tpp.[Price],
						[SumInvoiceProduct] = tpp.[SumInvoiceProduct],
						[ActualProductBaselineCaseQty] = tpp.[ActualProductBaselineCaseQty],
						[PlanProductBaselineVolume] = tpp.[PlanProductBaselineVolume],
						[PlanProductPostPromoEffectVolumeW1] = tpp.[PlanProductPostPromoEffectVolumeW1],
						[PlanProductPostPromoEffectVolumeW2] = tpp.[PlanProductPostPromoEffectVolumeW2],
						[PlanProductPostPromoEffectVolume] = tpp.[PlanProductPostPromoEffectVolume],
						[ActualProductQtySO] = tpp.[ActualProductQtySO]
					FROM
						(SELECT * FROM [DefaultSchemaSetting].[TEMP_PROMOPRODUCT]) AS tpp WHERE [DefaultSchemaSetting].[PromoProduct].[Id] = tpp.Id
		
					UPDATE [DefaultSchemaSetting].[PromoSupportPromo]
					SET
						[Disabled] = tpsp.[Disabled],
						[DeletedDate] = tpsp.[DeletedDate],
						[PromoId] = tpsp.[PromoId],
						[PromoSupportId] = tpsp.[PromoSupportId],
						[PlanCalculation] = tpsp.[PlanCalculation],
						[FactCalculation] = tpsp.[FactCalculation],
						[PlanCostProd] = tpsp.[PlanCostProd],
						[FactCostProd] = tpsp.[FactCostProd]
					FROM
						(SELECT * FROM [DefaultSchemaSetting].[TEMP_PROMOSUPPORTPROMO]) AS tpsp WHERE [DefaultSchemaSetting].[PromoSupportPromo].[Id] = tpsp.Id

					IF EXISTS (SELECT TOP 1 ProductId FROM [DefaultSchemaSetting].[ProductChangeIncident] WHERE NotificationProcessDate IS NULL)
					BEGIN
						INSERT INTO [DefaultSchemaSetting].[ProductChangeIncident]
							   ([ProductId]
							   ,[CreateDate]
							   ,[IsCreate]
							   ,[IsDelete]
							   ,[RecalculatedPromoId]
							   ,[AddedProductIds]
							   ,[ExcludedProductIds]
							   ,[IsRecalculated]
							   ,[Disabled])
						SELECT
							   (SELECT TOP 1 ProductId FROM [DefaultSchemaSetting].[ProductChangeIncident] WHERE NotificationProcessDate IS NULL)
							   ,GETDATE()
							   ,0
							   ,0
							   ,tpci.PromoId
							   ,tpci.AddedProductIds
							   ,tpci.ExcludedProductIds
							   ,1
							   ,0
						FROM [DefaultSchemaSetting].[TEMP_PRODUCTCHANGEINCIDENTS] AS tpci
					END
				END

			IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[DefaultSchemaSetting].[TEMP_PROMO]') AND type in (N'U'))
			DROP TABLE [DefaultSchemaSetting].[TEMP_PROMO]
			GO

			CREATE TABLE [DefaultSchemaSetting].[TEMP_PROMO](
				[Id] [uniqueidentifier] NOT NULL,
				[Disabled] [bit] NOT NULL,
				[DeletedDate] [datetimeoffset](7) NULL,
				[BrandId] [uniqueidentifier] NULL,
				[BrandTechId] [uniqueidentifier] NULL,
				[PromoStatusId] [uniqueidentifier] NULL,
				[Name] [nvarchar](255) NULL,
				[StartDate] [datetimeoffset](7) NULL,
				[EndDate] [datetimeoffset](7) NULL,
				[DispatchesStart] [datetimeoffset](7) NULL,
				[DispatchesEnd] [datetimeoffset](7) NULL,
				[ColorId] [uniqueidentifier] NULL,
				[Number] [int] NULL,
				[RejectReasonId] [uniqueidentifier] NULL,
				[EventId] [uniqueidentifier] NULL,
				[MarsMechanicId] [uniqueidentifier] NULL,
				[MarsMechanicTypeId] [uniqueidentifier] NULL,
				[PlanInstoreMechanicId] [uniqueidentifier] NULL,
				[PlanInstoreMechanicTypeId] [uniqueidentifier] NULL,
				[MarsMechanicDiscount] [float] NULL,
				[OtherEventName] [nvarchar](255) NULL,
				[EventName] [nvarchar](max) NULL,
				[ClientHierarchy] [nvarchar](max) NULL,
				[ProductHierarchy] [nvarchar](max) NULL,
				[CreatorId] [uniqueidentifier] NULL,
				[MarsStartDate] [nvarchar](15) NULL,
				[MarsEndDate] [nvarchar](15) NULL,
				[MarsDispatchesStart] [nvarchar](15) NULL,
				[MarsDispatchesEnd] [nvarchar](15) NULL,
				[ClientTreeId] [int] NULL,
				[BaseClientTreeId] [int] NULL,
				[Mechanic] [nvarchar](255) NULL,
				[MechanicIA] [nvarchar](255) NULL,
				[BaseClientTreeIds] [nvarchar](400) NULL,
				[LastApprovedDate] [datetimeoffset](7) NULL,
				[TechnologyId] [uniqueidentifier] NULL,
				[NeedRecountUplift] [bit] NULL,
				[IsAutomaticallyApproved] [bit] NULL,
				[IsCMManagerApproved] [bit] NULL,
				[IsDemandPlanningApproved] [bit] NULL,
				[IsDemandFinanceApproved] [bit] NULL,
				[PlanPromoXSites] [float] NULL,
				[PlanPromoCatalogue] [float] NULL,
				[PlanPromoPOSMInClient] [float] NULL,
				[PlanPromoCostProdXSites] [float] NULL,
				[PlanPromoCostProdCatalogue] [float] NULL,
				[PlanPromoCostProdPOSMInClient] [float] NULL,
				[ActualPromoXSites] [float] NULL,
				[ActualPromoCatalogue] [float] NULL,
				[ActualPromoPOSMInClient] [float] NULL,
				[ActualPromoCostProdXSites] [float] NULL,
				[ActualPromoCostProdCatalogue] [float] NULL,
				[ActualPromoCostProdPOSMInClient] [float] NULL,
				[MechanicComment] [nvarchar](255) NULL,
				[PlanInstoreMechanicDiscount] [float] NULL,
				[CalendarPriority] [int] NULL,
				[PlanPromoTIShopper] [float] NULL,
				[PlanPromoTIMarketing] [float] NULL,
				[PlanPromoBranding] [float] NULL,
				[PlanPromoCost] [float] NULL,
				[PlanPromoBTL] [float] NULL,
				[PlanPromoCostProduction] [float] NULL,
				[PlanPromoUpliftPercent] [float] NULL,
				[PlanPromoIncrementalLSV] [float] NULL,
				[PlanPromoLSV] [float] NULL,
				[PlanPromoROIPercent] [float] NULL,
				[PlanPromoIncrementalNSV] [float] NULL,
				[PlanPromoNetIncrementalNSV] [float] NULL,
				[PlanPromoIncrementalMAC] [float] NULL,
				[ActualPromoTIShopper] [float] NULL,
				[ActualPromoTIMarketing] [float] NULL,
				[ActualPromoBranding] [float] NULL,
				[ActualPromoBTL] [float] NULL,
				[ActualPromoCostProduction] [float] NULL,
				[ActualPromoCost] [float] NULL,
				[ActualPromoUpliftPercent] [float] NULL,
				[ActualPromoIncrementalLSV] [float] NULL,
				[ActualPromoLSV] [float] NULL,
				[ActualPromoROIPercent] [float] NULL,
				[ActualPromoIncrementalNSV] [float] NULL,
				[ActualPromoNetIncrementalNSV] [float] NULL,
				[ActualPromoIncrementalMAC] [float] NULL,
				[ActualInStoreMechanicId] [uniqueidentifier] NULL,
				[ActualInStoreMechanicTypeId] [uniqueidentifier] NULL,
				[PromoDuration] [int] NULL,
				[DispatchDuration] [int] NULL,
				[InvoiceNumber] [nvarchar](max) NULL,
				[PlanPromoBaselineLSV] [float] NULL,
				[PlanPromoIncrementalBaseTI] [float] NULL,
				[PlanPromoIncrementalCOGS] [float] NULL,
				[PlanPromoTotalCost] [float] NULL,
				[PlanPromoNetIncrementalLSV] [float] NULL,
				[PlanPromoNetLSV] [float] NULL,
				[PlanPromoNetIncrementalMAC] [float] NULL,
				[PlanPromoIncrementalEarnings] [float] NULL,
				[PlanPromoNetIncrementalEarnings] [float] NULL,
				[PlanPromoNetROIPercent] [float] NULL,
				[PlanPromoNetUpliftPercent] [float] NULL,
				[ActualPromoBaselineLSV] [float] NULL,
				[ActualInStoreDiscount] [float] NULL,
				[ActualInStoreShelfPrice] [float] NULL,
				[ActualPromoIncrementalBaseTI] [float] NULL,
				[ActualPromoIncrementalCOGS] [float] NULL,
				[ActualPromoTotalCost] [float] NULL,
				[ActualPromoNetIncrementalLSV] [float] NULL,
				[ActualPromoNetLSV] [float] NULL,
				[ActualPromoNetIncrementalMAC] [float] NULL,
				[ActualPromoIncrementalEarnings] [float] NULL,
				[ActualPromoNetIncrementalEarnings] [float] NULL,
				[ActualPromoNetROIPercent] [float] NULL,
				[ActualPromoNetUpliftPercent] [float] NULL,
				[Calculating] [bit] NULL,
				[BlockInformation] [nvarchar](max) NULL,
				[PlanPromoBaselineBaseTI] [float] NULL,
				[PlanPromoBaseTI] [float] NULL,
				[PlanPromoNetNSV] [float] NULL,
				[ActualPromoBaselineBaseTI] [float] NULL,
				[ActualPromoBaseTI] [float] NULL,
				[ActualPromoNetNSV] [float] NULL,
				[ProductSubrangesList] [nvarchar](500) NULL,
				[ClientTreeKeyId] [int] NULL,
				[InOut] [bit] NULL,
				[PlanPromoNetIncrementalBaseTI] [float] NULL,
				[PlanPromoNetIncrementalCOGS] [float] NULL,
				[ActualPromoNetIncrementalBaseTI] [float] NULL,
				[ActualPromoNetIncrementalCOGS] [float] NULL,
				[PlanPromoNetBaseTI] [float] NULL,
				[PlanPromoNSV] [float] NULL,
				[ActualPromoNetBaseTI] [float] NULL,
				[ActualPromoNSV] [float] NULL,
				[ActualPromoLSVByCompensation] [float] NULL,
				[PlanInStoreShelfPrice] [float] NULL,
				[PlanPromoPostPromoEffectLSVW1] [float] NULL,
				[PlanPromoPostPromoEffectLSVW2] [float] NULL,
				[PlanPromoPostPromoEffectLSV] [float] NULL,
				[ActualPromoPostPromoEffectLSVW1] [float] NULL,
				[ActualPromoPostPromoEffectLSVW2] [float] NULL,
				[ActualPromoPostPromoEffectLSV] [float] NULL,
				[LoadFromTLC] [bit] NOT NULL,
				[InOutProductIds] [nvarchar](max) NULL,
				[InOutExcludeAssortmentMatrixProductsButtonPressed] [bit] NOT NULL,
				[DocumentNumber] [nvarchar](max) NULL,
				[LastChangedDate] [datetimeoffset](7) NULL,
				[LastChangedDateDemand] [datetimeoffset](7) NULL,
				[LastChangedDateFinance] [datetimeoffset](7) NULL,
				[RegularExcludedProductIds] [nvarchar](max) NULL,
				[AdditionalUserTimestamp] [nvarchar](100) NULL,
				[IsGrowthAcceleration] [bit] NOT NULL,
				[PromoTypesId] [uniqueidentifier] NULL,
				[CreatorLogin] [nvarchar](max) NULL,
				[PlanTIBasePercent] [float] NULL,
				[PlanCOGSPercent] [float] NULL,
				[ActualTIBasePercent] [float] NULL,
				[ActualCOGSPercent] [float] NULL,
				[SumInvoice] [float] NULL,
				[IsOnInvoice] [bit] NOT NULL,
				[ActualPromoLSVSI] [float] NULL,
				[ActualPromoLSVSO] [float] NULL,
				[IsApolloExport] [bit] NOT NULL,
				[DeviationCoefficient] [float] NOT NULL,
				[UseActualTI] [bit] NOT NULL,
				[UseActualCOGS] [bit] NOT NULL,
				[BudgetYear] [int] NULL,
				[PlanAddTIShopperApproved] [float] NULL,
				[PlanAddTIShopperCalculated] [float] NULL,
				[PlanAddTIMarketingApproved] [float] NULL,
				[ActualAddTIShopper] [float] NULL,
				[ActualAddTIMarketing] [float] NULL,
				[ProductSubrangesListRU] [nvarchar](500) NULL,
				[ManualInputSumInvoice] [bit] NULL,
				[IsSplittable] [bit] NOT NULL,
				[PlanPromoBaselineVolume] [float] NULL,
				[PlanPromoPostPromoEffectVolume] [float] NULL,
				[PlanPromoPostPromoEffectVolumeW1] [float] NULL,
				[PlanPromoPostPromoEffectVolumeW2] [float] NULL,
				[PlanPromoIncrementalVolume] [float] NULL,
				[PlanPromoNetIncrementalVolume] [float] NULL,
				[ActualPromoBaselineVolume] [float] NULL,
				[ActualPromoPostPromoEffectVolume] [float] NULL,
				[ActualPromoVolumeByCompensation] [float] NULL,
				[ActualPromoVolumeSI] [float] NULL,
				[ActualPromoVolume] [float] NULL,
				[ActualPromoIncrementalVolume] [float] NULL,
				[ActualPromoNetIncrementalVolume] [float] NULL,
				[PlanPromoIncrementalCOGSTn] [float] NULL,
				[PlanPromoNetIncrementalCOGSTn] [float] NULL,
				[ActualPromoIncrementalCOGSTn] [float] NULL,
				[ActualPromoNetIncrementalCOGSTn] [float] NULL,
				[IsLSVBased] [bit] NOT NULL,
				[PlanPromoIncrementalMACLSV] [float] NULL,
				[PlanPromoNetIncrementalMACLSV] [float] NULL,
				[ActualPromoIncrementalMACLSV] [float] NULL,
				[ActualPromoNetIncrementalMACLSV] [float] NULL,
				[PlanPromoIncrementalEarningsLSV] [float] NULL,
				[PlanPromoNetIncrementalEarningsLSV] [float] NULL,
				[ActualPromoIncrementalEarningsLSV] [float] NULL,
				[ActualPromoNetIncrementalEarningsLSV] [float] NULL,
				[PlanPromoROIPercentLSV] [float] NULL,
				[PlanPromoNetROIPercentLSV] [float] NULL,
				[ActualPromoROIPercentLSV] [float] NULL,
				[ActualPromoNetROIPercentLSV] [float] NULL,
				[PlanCOGSTn] [float] NULL,
				[ActualCOGSTn] [float] NULL
			) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
			GO


			IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[DefaultSchemaSetting].[TEMP_PROMOPRODUCT]') AND type in (N'U'))
			DROP TABLE [DefaultSchemaSetting].[TEMP_PROMOPRODUCT]
			GO

			CREATE TABLE [DefaultSchemaSetting].[TEMP_PROMOPRODUCT](
				[Id] [uniqueidentifier] NOT NULL,
				[Disabled] [bit] NOT NULL,
				[DeletedDate] [datetimeoffset](7) NULL,
				[ZREP] [nvarchar](255) NULL,
				[PromoId] [uniqueidentifier] NOT NULL,
				[ProductId] [uniqueidentifier] NOT NULL,
				[EAN_Case] [nvarchar](255) NULL,
				[PlanProductPCQty] [int] NULL,
				[PlanProductPCLSV] [float] NULL,
				[ActualProductPCQty] [int] NULL,
				[ActualProductUOM] [nvarchar](max) NULL,
				[ActualProductSellInPrice] [float] NULL,
				[ActualProductShelfDiscount] [float] NULL,
				[ActualProductPCLSV] [float] NULL,
				[ActualProductUpliftPercent] [float] NULL,
				[ActualProductIncrementalPCQty] [float] NULL,
				[ActualProductIncrementalPCLSV] [float] NULL,
				[ActualProductIncrementalLSV] [float] NULL,
				[PlanProductUpliftPercent] [float] NULL,
				[ActualProductLSV] [float] NULL,
				[PlanProductBaselineLSV] [float] NULL,
				[ActualProductPostPromoEffectQty] [float] NULL,
				[PlanProductPostPromoEffectQty] [float] NULL,
				[ProductEN] [nvarchar](max) NULL,
				[PlanProductCaseQty] [float] NULL,
				[PlanProductBaselineCaseQty] [float] NULL,
				[ActualProductCaseQty] [float] NULL,
				[PlanProductPostPromoEffectLSVW1] [float] NULL,
				[PlanProductPostPromoEffectLSVW2] [float] NULL,
				[PlanProductPostPromoEffectLSV] [float] NULL,
				[ActualProductPostPromoEffectLSV] [float] NULL,
				[PlanProductIncrementalCaseQty] [float] NULL,
				[ActualProductPostPromoEffectQtyW1] [float] NULL,
				[ActualProductPostPromoEffectQtyW2] [float] NULL,
				[PlanProductPostPromoEffectQtyW1] [float] NULL,
				[PlanProductPostPromoEffectQtyW2] [float] NULL,
				[PlanProductPCPrice] [float] NULL,
				[ActualProductBaselineLSV] [float] NULL,
				[EAN_PC] [nvarchar](255) NULL,
				[PlanProductCaseLSV] [float] NULL,
				[ActualProductLSVByCompensation] [float] NULL,
				[PlanProductLSV] [float] NULL,
				[PlanProductIncrementalLSV] [float] NULL,
				[AverageMarker] [bit] NOT NULL,
				[Price] [float] NULL,
				[SumInvoiceProduct] [float] NULL,
				[ActualProductBaselineCaseQty] [float] NULL,
				[CreateDate] [datetimeoffset](7) NULL,
				[PlanProductBaselineVolume] [float] NULL,
				[PlanProductPostPromoEffectVolumeW1] [float] NULL,
				[PlanProductPostPromoEffectVolumeW2] [float] NULL,
				[PlanProductPostPromoEffectVolume] [float] NULL,
				[ActualProductQtySO] [float] NULL
			) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]
			GO
        ";
    }
}
