// <auto-generated />
namespace Module.Persist.TPM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Update_PromoView_Add_ShelfPrice_Discount : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Update_PromoView_Add_ShelfPrice_Discount));
        
        string IMigrationMetadata.Id
        {
            get { return "202201261747552_Update_PromoView_Add_ShelfPrice_Discount"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
