// <auto-generated />
namespace Module.Persist.TPM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class RollingScenario_AP_and_Mode_PromoViews : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RollingScenario_AP_and_Mode_PromoViews));
        
        string IMigrationMetadata.Id
        {
            get { return "202207190856419_RollingScenario_AP_and_Mode_PromoViews"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
