// <auto-generated />
namespace Module.Persist.TPM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Aftermigration_changeview : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Aftermigration_changeview));
        
        string IMigrationMetadata.Id
        {
            get { return "202208120912546_Aftermigration_changeview"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
