// <auto-generated />
namespace Module.Persist.TPM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Product_Case_PC_Volume_Fields : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Product_Case_PC_Volume_Fields));
        
        string IMigrationMetadata.Id
        {
            get { return "202205060635322_Product_Case_PC_Volume_Fields"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
