// <auto-generated />
namespace Module.Persist.TPM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Add_IsSplittable_In_Promo : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_IsSplittable_In_Promo));
        
        string IMigrationMetadata.Id
        {
            get { return "202203292006307_Add_IsSplittable_In_Promo"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
