// <auto-generated />
namespace Module.Persist.TPM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class PriceList_FDM_Add_Realease_Status : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(PriceList_FDM_Add_Realease_Status));
        
        string IMigrationMetadata.Id
        {
            get { return "202209160719344_PriceList_FDM_Add_Realease_Status"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
