// <auto-generated />
namespace Module.Persist.TPM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class Rename_Volume_to_TonCost : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Rename_Volume_to_TonCost));
        
        string IMigrationMetadata.Id
        {
            get { return "202205131809217_Rename_Volume_to_TonCost"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
