// <auto-generated />
namespace Module.Persist.TPM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Empty_ML_PriceIncrease : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Empty_ML_PriceIncrease));
        
        string IMigrationMetadata.Id
        {
            get { return "202304050724113_Empty_ML_PriceIncrease"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
