// <auto-generated />
namespace Module.Persist.TPM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class RA_mode_AccessPoints : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(RA_mode_AccessPoints));
        
        string IMigrationMetadata.Id
        {
            get { return "202306290644396_RA_mode_AccessPoints"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
