// <auto-generated />
namespace Module.Persist.TPM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Exclude_Hidden_From_View : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Exclude_Hidden_From_View));
        
        string IMigrationMetadata.Id
        {
            get { return "202306231047528_Exclude_Hidden_From_View"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
