// <auto-generated />
namespace Module.Persist.TPM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Empty_Migration_After_Merge_Sprin25 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Empty_Migration_After_Merge_Sprin25));
        
        string IMigrationMetadata.Id
        {
            get { return "202309100858584_Empty_Migration_After_Merge_Sprin25"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
