namespace Module.Persist.TPM.Migrations
{
    using Core.Settings;
    using System;
    using System.Data.Entity.Migrations;
    
    public partial class ModifiedDate : DbMigration
    {
        public override void Up()
        {
            var defaultSchema = AppSettingsManager.GetSetting<string>("DefaultSchema", "dbo");
            AddColumn($"{defaultSchema}.Category", "ModifiedDate", c => c.DateTimeOffset(precision: 7));
            AddColumn($"{defaultSchema}.Brand", "ModifiedDate", c => c.DateTimeOffset(precision: 7));
            AddColumn($"{defaultSchema}.BrandTech", "ModifiedDate", c => c.DateTimeOffset(precision: 7));
            AddColumn($"{defaultSchema}.ClientTreeBrandTech", "ModifiedDate", c => c.DateTimeOffset(precision: 7));
            AddColumn($"{defaultSchema}.ClientTree", "ModifiedDate", c => c.DateTimeOffset(precision: 7));
            AddColumn($"{defaultSchema}.AssortmentMatrix", "ModifiedDate", c => c.DateTimeOffset(precision: 7));
            AddColumn($"{defaultSchema}.Product", "ModifiedDate", c => c.DateTimeOffset(precision: 7));
            AddColumn($"{defaultSchema}.Mechanic", "ModifiedDate", c => c.DateTimeOffset(precision: 7));
            AddColumn($"{defaultSchema}.NoneNego", "ModifiedDate", c => c.DateTimeOffset(precision: 7));
            AddColumn($"{defaultSchema}.MechanicType", "ModifiedDate", c => c.DateTimeOffset(precision: 7));
            AddColumn($"{defaultSchema}.ProductTree", "ModifiedDate", c => c.DateTimeOffset(precision: 7));
            AddColumn($"{defaultSchema}.Technology", "ModifiedDate", c => c.DateTimeOffset(precision: 7));
            AddColumn($"{defaultSchema}.PromoTypes", "ModifiedDate", c => c.DateTimeOffset(precision: 7));
            AddColumn($"{defaultSchema}.BTLPromo", "ModifiedDate", c => c.DateTimeOffset(precision: 7));
            AddColumn($"{defaultSchema}.BTL", "ModifiedDate", c => c.DateTimeOffset(precision: 7));
            AddColumn($"{defaultSchema}.Event", "ModifiedDate", c => c.DateTimeOffset(precision: 7));
            AddColumn($"{defaultSchema}.EventClientTree", "ModifiedDate", c => c.DateTimeOffset(precision: 7));
            AddColumn($"{defaultSchema}.EventType", "ModifiedDate", c => c.DateTimeOffset(precision: 7));
            AddColumn($"{defaultSchema}.Color", "ModifiedDate", c => c.DateTimeOffset(precision: 7));
            AddColumn($"{defaultSchema}.CurrentDayIncremental", "ModifiedDate", c => c.DateTimeOffset(precision: 7));
            AddColumn($"{defaultSchema}.PromoApprovedIncident", "ModifiedDate", c => c.DateTimeOffset(precision: 7));
            AddColumn($"{defaultSchema}.PromoCancelledIncident", "ModifiedDate", c => c.DateTimeOffset(precision: 7));
            AddColumn($"{defaultSchema}.PromoOnApprovalIncident", "ModifiedDate", c => c.DateTimeOffset(precision: 7));
            AddColumn($"{defaultSchema}.PromoOnRejectIncident", "ModifiedDate", c => c.DateTimeOffset(precision: 7));
            AddColumn($"{defaultSchema}.PromoProductTree", "ModifiedDate", c => c.DateTimeOffset(precision: 7));
            AddColumn($"{defaultSchema}.PromoStatus", "ModifiedDate", c => c.DateTimeOffset(precision: 7));
            AddColumn($"{defaultSchema}.PromoStatusChange", "ModifiedDate", c => c.DateTimeOffset(precision: 7));
            AddColumn($"{defaultSchema}.RejectReason", "ModifiedDate", c => c.DateTimeOffset(precision: 7));
            AddColumn($"{defaultSchema}.PromoSupportPromo", "ModifiedDate", c => c.DateTimeOffset(precision: 7));
            AddColumn($"{defaultSchema}.BudgetSubItem", "ModifiedDate", c => c.DateTimeOffset(precision: 7));
            AddColumn($"{defaultSchema}.BudgetItem", "ModifiedDate", c => c.DateTimeOffset(precision: 7));
            AddColumn($"{defaultSchema}.Budget", "ModifiedDate", c => c.DateTimeOffset(precision: 7));
            AddColumn($"{defaultSchema}.NonPromoEquipment", "ModifiedDate", c => c.DateTimeOffset(precision: 7));
            AddColumn($"{defaultSchema}.BudgetSubItemClientTree", "ModifiedDate", c => c.DateTimeOffset(precision: 7));
            AddColumn($"{defaultSchema}.PromoUpliftFailIncident", "ModifiedDate", c => c.DateTimeOffset(precision: 7));
            AddColumn($"{defaultSchema}.RollingScenario", "ModifiedDate", c => c.DateTimeOffset(precision: 7));
            AddColumn($"{defaultSchema}.PriceList", "ModifiedDate", c => c.DateTimeOffset(precision: 7));
            AddColumn($"{defaultSchema}.RollingVolume", "ModifiedDate", c => c.DateTimeOffset(precision: 7));
            AddColumn($"{defaultSchema}.CompetitorPromo", "ModifiedDate", c => c.DateTimeOffset(precision: 7));
            AddColumn($"{defaultSchema}.Competitor", "ModifiedDate", c => c.DateTimeOffset(precision: 7));
            AddColumn($"{defaultSchema}.CompetitorBrandTech", "ModifiedDate", c => c.DateTimeOffset(precision: 7));
            AddColumn($"{defaultSchema}.Plu", "ModifiedDate", c => c.DateTimeOffset(precision: 7));
            AddColumn($"{defaultSchema}.RATIShopper", "ModifiedDate", c => c.DateTimeOffset(precision: 7));
            AddColumn($"{defaultSchema}.TradeInvestment", "ModifiedDate", c => c.DateTimeOffset(precision: 7));
            AddColumn($"{defaultSchema}.CoefficientSI2SO", "ModifiedDate", c => c.DateTimeOffset(precision: 7));
            AddColumn($"{defaultSchema}.Segment", "ModifiedDate", c => c.DateTimeOffset(precision: 7));
            AddColumn($"{defaultSchema}.TechHighLevel", "ModifiedDate", c => c.DateTimeOffset(precision: 7));
            AddColumn($"{defaultSchema}.Format", "ModifiedDate", c => c.DateTimeOffset(precision: 7));
            AddColumn($"{defaultSchema}.Subrange", "ModifiedDate", c => c.DateTimeOffset(precision: 7));
            AddColumn($"{defaultSchema}.AgeGroup", "ModifiedDate", c => c.DateTimeOffset(precision: 7));
            AddColumn($"{defaultSchema}.Variety", "ModifiedDate", c => c.DateTimeOffset(precision: 7));
            AddColumn($"{defaultSchema}.Region", "ModifiedDate", c => c.DateTimeOffset(precision: 7));
            AddColumn($"{defaultSchema}.CommercialNet", "ModifiedDate", c => c.DateTimeOffset(precision: 7));
            AddColumn($"{defaultSchema}.CommercialSubnet", "ModifiedDate", c => c.DateTimeOffset(precision: 7));
            AddColumn($"{defaultSchema}.Distributor", "ModifiedDate", c => c.DateTimeOffset(precision: 7));
            AddColumn($"{defaultSchema}.StoreType", "ModifiedDate", c => c.DateTimeOffset(precision: 7));
            AddColumn($"{defaultSchema}.Sale", "ModifiedDate", c => c.DateTimeOffset(precision: 7));
            AddColumn($"{defaultSchema}.NodeType", "ModifiedDate", c => c.DateTimeOffset(precision: 7));
            AddColumn($"{defaultSchema}.PromoDemand", "ModifiedDate", c => c.DateTimeOffset(precision: 7));
            AddColumn($"{defaultSchema}.RetailType", "ModifiedDate", c => c.DateTimeOffset(precision: 7));
            AddColumn($"{defaultSchema}.ExportQuery", "ModifiedDate", c => c.DateTimeOffset(precision: 7));
            AddColumn($"{defaultSchema}.PromoDemandChangeIncident", "ModifiedDate", c => c.DateTimeOffset(precision: 7));
            AddColumn($"{defaultSchema}.ServiceInfo", "ModifiedDate", c => c.DateTimeOffset(precision: 7));
            AddColumn($"{defaultSchema}.PostPromoEffect", "ModifiedDate", c => c.DateTimeOffset(precision: 7));
            AddColumn($"{defaultSchema}.COGS", "ModifiedDate", c => c.DateTimeOffset(precision: 7));
            AddColumn($"{defaultSchema}.PlanCOGSTn", "ModifiedDate", c => c.DateTimeOffset(precision: 7));
            AddColumn($"{defaultSchema}.BlockedPromo", "ModifiedDate", c => c.DateTimeOffset(precision: 7));
            AddColumn($"{defaultSchema}.ChangesIncident", "ModifiedDate", c => c.DateTimeOffset(precision: 7));
            AddColumn($"{defaultSchema}.ClientTreeNeedUpdateIncident", "ModifiedDate", c => c.DateTimeOffset(precision: 7));
            AddColumn($"{defaultSchema}.ActualCOGS", "ModifiedDate", c => c.DateTimeOffset(precision: 7));
            AddColumn($"{defaultSchema}.ActualCOGSTn", "ModifiedDate", c => c.DateTimeOffset(precision: 7));
            AddColumn($"{defaultSchema}.ActualTradeInvestment", "ModifiedDate", c => c.DateTimeOffset(precision: 7));
            AddColumn($"{defaultSchema}.ClientDashboard", "ModifiedDate", c => c.DateTimeOffset(precision: 7));
            AddColumn($"{defaultSchema}.NonPromoSupportDMP", "ModifiedDate", c => c.DateTimeOffset(precision: 7));
            AddColumn($"{defaultSchema}.PromoSupportDMP", "ModifiedDate", c => c.DateTimeOffset(precision: 7));
            AddColumn($"{defaultSchema}.RPASetting", "ModifiedDate", c => c.DateTimeOffset(precision: 7));
            AddColumn($"{defaultSchema}.RPA", "ModifiedDate", c => c.DateTimeOffset(precision: 7));
            AddColumn($"{defaultSchema}.MetricsLiveHistories", "ModifiedDate", c => c.DateTimeOffset(precision: 7));
        }
        
        public override void Down()
        {
            var defaultSchema = AppSettingsManager.GetSetting<string>("DefaultSchema", "dbo");
            DropColumn($"{defaultSchema}.MetricsLiveHistories", "ModifiedDate");
            DropColumn($"{defaultSchema}.RPA", "ModifiedDate");
            DropColumn($"{defaultSchema}.RPASetting", "ModifiedDate");
            DropColumn($"{defaultSchema}.PromoSupportDMP", "ModifiedDate");
            DropColumn($"{defaultSchema}.NonPromoSupportDMP", "ModifiedDate");
            DropColumn($"{defaultSchema}.ClientDashboard", "ModifiedDate");
            DropColumn($"{defaultSchema}.ActualTradeInvestment", "ModifiedDate");
            DropColumn($"{defaultSchema}.ActualCOGSTn", "ModifiedDate");
            DropColumn($"{defaultSchema}.ActualCOGS", "ModifiedDate");
            DropColumn($"{defaultSchema}.ClientTreeNeedUpdateIncident", "ModifiedDate");
            DropColumn($"{defaultSchema}.ChangesIncident", "ModifiedDate");
            DropColumn($"{defaultSchema}.BlockedPromo", "ModifiedDate");
            DropColumn($"{defaultSchema}.PlanCOGSTn", "ModifiedDate");
            DropColumn($"{defaultSchema}.COGS", "ModifiedDate");
            DropColumn($"{defaultSchema}.PostPromoEffect", "ModifiedDate");
            DropColumn($"{defaultSchema}.ServiceInfo", "ModifiedDate");
            DropColumn($"{defaultSchema}.PromoDemandChangeIncident", "ModifiedDate");
            DropColumn($"{defaultSchema}.ExportQuery", "ModifiedDate");
            DropColumn($"{defaultSchema}.RetailType", "ModifiedDate");
            DropColumn($"{defaultSchema}.PromoDemand", "ModifiedDate");
            DropColumn($"{defaultSchema}.NodeType", "ModifiedDate");
            DropColumn($"{defaultSchema}.Sale", "ModifiedDate");
            DropColumn($"{defaultSchema}.StoreType", "ModifiedDate");
            DropColumn($"{defaultSchema}.Distributor", "ModifiedDate");
            DropColumn($"{defaultSchema}.CommercialSubnet", "ModifiedDate");
            DropColumn($"{defaultSchema}.CommercialNet", "ModifiedDate");
            DropColumn($"{defaultSchema}.Region", "ModifiedDate");
            DropColumn($"{defaultSchema}.Variety", "ModifiedDate");
            DropColumn($"{defaultSchema}.AgeGroup", "ModifiedDate");
            DropColumn($"{defaultSchema}.Subrange", "ModifiedDate");
            DropColumn($"{defaultSchema}.Format", "ModifiedDate");
            DropColumn($"{defaultSchema}.TechHighLevel", "ModifiedDate");
            DropColumn($"{defaultSchema}.Segment", "ModifiedDate");
            DropColumn($"{defaultSchema}.CoefficientSI2SO", "ModifiedDate");
            DropColumn($"{defaultSchema}.TradeInvestment", "ModifiedDate");
            DropColumn($"{defaultSchema}.RATIShopper", "ModifiedDate");
            DropColumn($"{defaultSchema}.Plu", "ModifiedDate");
            DropColumn($"{defaultSchema}.CompetitorBrandTech", "ModifiedDate");
            DropColumn($"{defaultSchema}.Competitor", "ModifiedDate");
            DropColumn($"{defaultSchema}.CompetitorPromo", "ModifiedDate");
            DropColumn($"{defaultSchema}.RollingVolume", "ModifiedDate");
            DropColumn($"{defaultSchema}.PriceList", "ModifiedDate");
            DropColumn($"{defaultSchema}.RollingScenario", "ModifiedDate");
            DropColumn($"{defaultSchema}.PromoUpliftFailIncident", "ModifiedDate");
            DropColumn($"{defaultSchema}.BudgetSubItemClientTree", "ModifiedDate");
            DropColumn($"{defaultSchema}.NonPromoEquipment", "ModifiedDate");
            DropColumn($"{defaultSchema}.Budget", "ModifiedDate");
            DropColumn($"{defaultSchema}.BudgetItem", "ModifiedDate");
            DropColumn($"{defaultSchema}.BudgetSubItem", "ModifiedDate");
            DropColumn($"{defaultSchema}.PromoSupportPromo", "ModifiedDate");
            DropColumn($"{defaultSchema}.RejectReason", "ModifiedDate");
            DropColumn($"{defaultSchema}.PromoStatusChange", "ModifiedDate");
            DropColumn($"{defaultSchema}.PromoStatus", "ModifiedDate");
            DropColumn($"{defaultSchema}.PromoProductTree", "ModifiedDate");
            DropColumn($"{defaultSchema}.PromoOnRejectIncident", "ModifiedDate");
            DropColumn($"{defaultSchema}.PromoOnApprovalIncident", "ModifiedDate");
            DropColumn($"{defaultSchema}.PromoCancelledIncident", "ModifiedDate");
            DropColumn($"{defaultSchema}.PromoApprovedIncident", "ModifiedDate");
            DropColumn($"{defaultSchema}.CurrentDayIncremental", "ModifiedDate");
            DropColumn($"{defaultSchema}.Color", "ModifiedDate");
            DropColumn($"{defaultSchema}.EventType", "ModifiedDate");
            DropColumn($"{defaultSchema}.EventClientTree", "ModifiedDate");
            DropColumn($"{defaultSchema}.Event", "ModifiedDate");
            DropColumn($"{defaultSchema}.BTL", "ModifiedDate");
            DropColumn($"{defaultSchema}.BTLPromo", "ModifiedDate");
            DropColumn($"{defaultSchema}.PromoTypes", "ModifiedDate");
            DropColumn($"{defaultSchema}.Technology", "ModifiedDate");
            DropColumn($"{defaultSchema}.ProductTree", "ModifiedDate");
            DropColumn($"{defaultSchema}.MechanicType", "ModifiedDate");
            DropColumn($"{defaultSchema}.NoneNego", "ModifiedDate");
            DropColumn($"{defaultSchema}.Mechanic", "ModifiedDate");
            DropColumn($"{defaultSchema}.Product", "ModifiedDate");
            DropColumn($"{defaultSchema}.AssortmentMatrix", "ModifiedDate");
            DropColumn($"{defaultSchema}.ClientTree", "ModifiedDate");
            DropColumn($"{defaultSchema}.ClientTreeBrandTech", "ModifiedDate");
            DropColumn($"{defaultSchema}.BrandTech", "ModifiedDate");
            DropColumn($"{defaultSchema}.Brand", "ModifiedDate");
            DropColumn($"{defaultSchema}.Category", "ModifiedDate");
        }
    }
}
