// <auto-generated />
namespace Module.Persist.TPM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class AddPromoesToSavedScenario : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddPromoesToSavedScenario));
        
        string IMigrationMetadata.Id
        {
            get { return "202307041158509_AddPromoesToSavedScenario"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
