// <auto-generated />
namespace Module.Persist.TPM.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.4")]
    public sealed partial class Add_budgetYear_PromoViewRS : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(Add_budgetYear_PromoViewRS));
        
        string IMigrationMetadata.Id
        {
            get { return "202306261055558_Add_budgetYear_PromoViewRS"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
