name: $(tfProjectName)_$(date:yyyyMMdd)$(rev:.r)

trigger:
 paths:
   include:
     - 'JupiterYandex/terraform/*'
 branches:
   include:
    - develop

variables:
  AgentName1: $(Agent.Name)

stages:
- stage: Plan
  jobs:
  - job: PlanJob
    steps:

    - bash: |
        echo "Agent Name: $(Agent.Name)"
        echo "##vso[task.setvariable variable=AgentName;isoutput=true]$(Agent.Name)"
      name: passOutput

- stage: Apply
  dependsOn: [Plan]
  # condition: and(succeeded('Plan'), eq(variables['tfDestroyEnvironment'], false))
  jobs:
  - job: Apply
    # variables:
      # AgentName: $[ stageDependencies.Plan.PlanJob.outputs['passOutput.AgentName'] ]
    # pool:
      # name: SMARTCOM_UBDS05
      # demands: Agent.Name -equals $(AgentName)   
    steps:
    - bash: |
        echo $(AgentName)
        echo $(AgentName1)

