Ext.define('App.model.tpm.promoroireport.PromoROIReport', {
    extend: 'Ext.data.Model',
    idProperty: 'Id',
    breezeEntityType: 'Promo',
    fields: [
        { name: 'Number', type: 'int', hidden: false, isDefault: true },
        { name: 'Client1LevelName', type: 'string', hidden: false, isDefault: true },//NA/RKA (1 level)
        { name: 'Client2LevelName', type: 'string', hidden: false, isDefault: true },//Client Group (2 level)
        { name: 'ClientName', type: 'string', hidden: false, isDefault: true },//Client (3 level)
        { name: 'BrandName', type: 'string', hidden: false, isDefault: false },
        { name: 'TechnologyName', hidden: false, isDefault: false },//Product (2 level)
        { name: 'ProductSubrangesList', type: 'string', hidden: false, isDefault: true },//Product (3 level)
        { name: 'MarsMechanicName', type: 'string', hidden: false, isDefault: true },
        { name: 'MarsMechanicTypeName', type: 'string', hidden: true, isDefault: true },
        { name: 'MarsMechanicDiscount', type: 'float', hidden: false, isDefault: true },
        { name: 'MechanicComment', type: 'string', hidden: false, isDefault: true },
        { name: 'StartDate', useNull: true, type: 'date', hidden: false, isDefault: true },
        { name: 'EndDate', useNull: true, type: 'date', hidden: false, isDefault: true },
        { name: 'PromoDuration', useNull: true, type: 'int', hidden: false, isDefault: true },
        { name: 'EventName', type: 'string', hidden: false, isDefault: true },
        { name: 'PromoStatusName', type: 'string', hidden: false, isDefault: true },
        { name: 'InOut', useNull: true, type: 'bool', hidden: false, isDefault: true },
        { name: 'PlanInstoreMechanicName', type: 'string', type: 'string', hidden: true, isDefault: true },
        { name: 'PlanInstoreMechanicTypeName', type: 'string', type: 'string', hidden: true, isDefault: true },
        { name: 'PlanInstoreMechanicDiscount', type: 'float', hidden: false, isDefault: true },
        { name: 'PlanInStoreShelfPrice', useNull: true, type: 'float', hidden: false, isDefault: true },
        // [{ name: 'PcPrice' }] 19
        { name: 'PCPrice', useNull: true, type: 'float', hidden: false, isDefault: true },
        { name: 'PlanPromoBaselineLSV', useNull: true, type: 'float', hidden: false, isDefault: true },
        { name: 'PlanPromoIncrementalLSV', useNull: true, type: 'float', hidden: false, isDefault: true },
        { name: 'PlanPromoLSV', useNull: true, type: 'float', hidden: false, isDefault: true },
        { name: 'PlanPromoUpliftPercent', useNull: true, type: 'float', hidden: false, isDefault: true },
        { name: 'PlanPromoTIShopper', useNull: true, type: 'float', hidden: false, isDefault: true },
        { name: 'PlanPromoTIMarketing', useNull: true, type: 'float', hidden: false, isDefault: true },
        { name: 'PlanPromoXSites', useNull: true, type: 'float', hidden: false, isDefault: true },
        { name: 'PlanPromoCatalogue', useNull: true, type: 'float', hidden: false, isDefault: true },
        { name: 'PlanPromoPOSMInClient', useNull: true, type: 'float', hidden: false, isDefault: true },
        { name: 'PlanPromoBranding', useNull: true, type: 'float', hidden: false, isDefault: true },
        { name: 'PlanPromoBTL', useNull: true, type: 'float', hidden: false, isDefault: true },
        { name: 'PlanPromoCostProduction', useNull: true, type: 'float', hidden: false, isDefault: true },
        { name: 'PlanPromoCostProdXSites', useNull: true, type: 'float', hidden: false, isDefault: true },
        { name: 'PlanPromoCostProdCatalogue', useNull: true, type: 'float', hidden: false, isDefault: true },
        { name: 'PlanPromoCostProdPOSMInClient', useNull: true, type: 'float', hidden: false, isDefault: true },
        { name: 'PlanPromoCost', useNull: true, type: 'float', hidden: false, isDefault: true },
        // [{ name: 'TI Base' }] 36
        { name: 'TIBasePercent', useNull: true, type: 'float', hidden: false, isDefault: true },
        { name: 'PlanPromoIncrementalBaseTI', useNull: true, type: 'float', hidden: false, isDefault: true },
        { name: 'PlanPromoNetIncrementalBaseTI', useNull: true, type: 'float', hidden: false, isDefault: true },
        // [{ name: 'COGS' }] 39
        { name: 'COGSPercent', useNull: true, type: 'float', hidden: false, isDefault: true },
        { name: 'PlanPromoIncrementalCOGS', useNull: true, type: 'float', hidden: false, isDefault: true },
        { name: 'PlanPromoNetIncrementalCOGS', useNull: true, type: 'float', hidden: false, isDefault: true },
        { name: 'PlanPromoTotalCost', useNull: true, type: 'float', hidden: false, isDefault: true },
        { name: 'PlanPromoPostPromoEffectLSV', useNull: true, type: 'float', hidden: false, isDefault: true },
        { name: 'PlanPromoNetIncrementalLSV', useNull: true, type: 'float', hidden: false, isDefault: true },
        { name: 'PlanPromoNetLSV', useNull: true, type: 'float', hidden: false, isDefault: true },
        { name: 'PlanPromoBaselineBaseTI', useNull: true, type: 'float', hidden: false, isDefault: true },
        { name: 'PlanPromoBaseTI', useNull: true, type: 'float', hidden: false, isDefault: true },
        { name: 'PlanPromoNetBaseTI', useNull: true, type: 'float', hidden: false, isDefault: true },
        { name: 'PlanPromoNSV', useNull: true, type: 'float', hidden: false, isDefault: true },
        { name: 'PlanPromoNetNSV', useNull: true, type: 'float', hidden: false, isDefault: true },
        { name: 'PlanPromoIncrementalNSV', useNull: true, type: 'float', hidden: false, isDefault: true },
        { name: 'PlanPromoNetIncrementalNSV', useNull: true, type: 'float', hidden: false, isDefault: true },
        { name: 'PlanPromoIncrementalMAC', useNull: true, type: 'float', hidden: false, isDefault: true },
        { name: 'PlanPromoNetIncrementalMAC', useNull: true, type: 'float', hidden: false, isDefault: true },
        { name: 'PlanPromoIncrementalEarnings', useNull: true, type: 'float', hidden: false, isDefault: true },
        { name: 'PlanPromoNetIncrementalEarnings', useNull: true, type: 'float', hidden: false, isDefault: true },
        { name: 'PlanPromoROIPercent', useNull: true, type: 'float', hidden: false, isDefault: true },
        { name: 'PlanPromoNetROIPercent', useNull: true, type: 'float', hidden: false, isDefault: true },
        { name: 'PlanPromoNetUpliftPercent', useNull: true, type: 'float', hidden: false, isDefault: true },
        { name: 'ActualInStoreMechanicName', type: 'string', hidden: true, isDefault: true },
        { name: 'ActualInStoreMechanicTypeName', type: 'string', hidden: true, isDefault: true },
        { name: 'ActualInStoreDiscount', type: 'float', hidden: false, isDefault: true },
        { name: 'ActualInStoreShelfPrice', useNull: true, type: 'float', hidden: false, isDefault: true },
        { name: 'InvoiceNumber', type: 'string', hidden: false, isDefault: true },
        { name: 'ActualPromoBaselineLSV', useNull: true, type: 'float', hidden: false, isDefault: true },
        { name: 'ActualPromoIncrementalLSV', useNull: true, type: 'float', hidden: false, isDefault: true },
        { name: 'ActualPromoLSVByCompensation', useNull: true, type: 'float', hidden: false, isDefault: true },
        { name: 'ActualPromoLSV', useNull: true, defaultValue: 0, type: 'float', hidden: false, isDefault: true },
        { name: 'ActualPromoUpliftPercent', useNull: true, type: 'float', hidden: false, isDefault: true },
        { name: 'ActualPromoNetUpliftPercent', useNull: true, type: 'float', hidden: false, isDefault: true },
        { name: 'ActualPromoTIShopper', useNull: true, type: 'float', hidden: false, isDefault: true },
        { name: 'ActualPromoTIMarketing', useNull: true, type: 'float', hidden: false, isDefault: true },
        { name: 'ActualPromoXSites', useNull: true, type: 'float', hidden: false, isDefault: true },
        { name: 'ActualPromoCatalogue', useNull: true, type: 'float', hidden: false, isDefault: true },
        { name: 'ActualPromoPOSMInClient', useNull: true, type: 'float', hidden: false, isDefault: true },
        { name: 'ActualPromoBranding', useNull: true, type: 'float', hidden: false, isDefault: true },
        { name: 'ActualPromoBTL', useNull: true, type: 'float', hidden: false, isDefault: true },
        { name: 'ActualPromoCostProduction', useNull: true, type: 'float', hidden: false, isDefault: true },
        { name: 'ActualPromoCostProdXSites', useNull: true, type: 'float', hidden: false, isDefault: true },
        { name: 'ActualPromoCostProdCatalogue', useNull: true, type: 'float', hidden: false, isDefault: true },
        { name: 'ActualPromoCostProdPOSMInClient', useNull: true, type: 'float', hidden: false, isDefault: true },
        { name: 'ActualPromoCost', useNull: true, type: 'float', hidden: false, isDefault: true },
        { name: 'ActualPromoIncrementalBaseTI', useNull: true, type: 'float', hidden: false, isDefault: true },
        { name: 'ActualPromoNetIncrementalBaseTI', useNull: true, type: 'float', hidden: false, isDefault: true },
        { name: 'ActualPromoIncrementalCOGS', useNull: true, type: 'float', hidden: false, isDefault: true },
        { name: 'ActualPromoNetIncrementalCOGS', useNull: true, type: 'float', hidden: false, isDefault: true },
        { name: 'ActualPromoTotalCost', useNull: true, type: 'float', hidden: false, isDefault: true },
        { name: 'ActualPromoPostPromoEffectLSV', useNull: true, type: 'float', hidden: false, isDefault: true },
        { name: 'ActualPromoNetIncrementalLSV', useNull: true, type: 'float', hidden: false, isDefault: true },
        { name: 'ActualPromoNetLSV', useNull: true, type: 'float', hidden: false, isDefault: true },
        { name: 'ActualPromoIncrementalNSV', useNull: true, type: 'float', hidden: false, isDefault: true },
        { name: 'ActualPromoNetIncrementalNSV', useNull: true, type: 'float', hidden: false, isDefault: true },
        { name: 'ActualPromoBaselineBaseTI', useNull: true, type: 'float', hidden: false, isDefault: true },
        { name: 'ActualPromoBaseTI', useNull: true, type: 'float', hidden: false, isDefault: true },
        { name: 'ActualPromoNetBaseTI', useNull: true, type: 'float', hidden: false, isDefault: true },
        { name: 'ActualPromoNSV', useNull: true, type: 'float', hidden: false, isDefault: true },
        { name: 'ActualPromoNetNSV', useNull: true, type: 'float', hidden: false, isDefault: true },
        { name: 'ActualPromoIncrementalMAC', useNull: true, type: 'float', hidden: false, isDefault: true },
        { name: 'ActualPromoNetIncrementalMAC', useNull: true, type: 'float', hidden: false, isDefault: true },
        { name: 'ActualPromoIncrementalEarnings', useNull: true, type: 'float', hidden: false, isDefault: true },
        { name: 'ActualPromoNetIncrementalEarnings', useNull: true, type: 'float', hidden: false, isDefault: true },
        { name: 'ActualPromoROIPercent', useNull: true, type: 'float', hidden: false, isDefault: true },
        { name: 'ActualPromoNetROIPercent', useNull: true, type: 'float', hidden: false, isDefault: true },
    ],
    proxy: {
        type: 'breeze',
        resourceName: 'PromoROIReports',
        reader: {
            type: 'json',
            totalProperty: 'inlineCount',
            root: 'results'
        }
    },
});