Ext.define('App.view.tpm.promopriceincreaseroireport.PromoROIReportEditor', {
    extend: 'App.view.core.common.EditorDetailWindow',
    alias: 'widget.promoroireporteditor',
    width: 1000,
    minWidth: 1000,
    maxHeight: 500,
    cls: 'readOnlyFields',

    noChange: true,

    items: {
        xtype: 'editorform',
        columnsCount: 2,
        items: [
            { xtype: 'numberfield', name: 'Number', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('Number') },
            { xtype: 'textfield', name: 'Client1LevelName', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('Client1LevelName') },
            { xtype: 'textfield', name: 'Client2LevelName', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('Client2LevelName') },
            { xtype: 'textfield', name: 'ClientName', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('ClientName') },
            { xtype: 'textfield', name: 'BrandName', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('BrandName') },
            { xtype: 'textfield', name: 'TechnologyName', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('TechnologyName') },
            { xtype: 'textfield', name: 'SubName', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('SubName') },
            { xtype: 'textfield', name: 'ProductSubrangesList', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('ProductSubrangesList') },
            { xtype: 'textfield', name: 'MarsMechanicName', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('MarsMechanicName') },
            { xtype: 'textfield', name: 'MarsMechanicTypeName', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('MarsMechanicTypeName') },
            { xtype: 'numberfield', name: 'MarsMechanicDiscount', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('MarsMechanicDiscount') },
            { xtype: 'textfield', name: 'MechanicComment', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('MechanicComment') },
            { xtype: 'datefield', name: 'StartDate', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('StartDate') },
            { xtype: 'textfield', name: 'MarsStartDate', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('MarsStartDate') },
            { xtype: 'datefield', name: 'EndDate', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('EndDate') },
            { xtype: 'textfield', name: 'MarsEndDate', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('MarsEndDate') },
            { xtype: 'numberfield', name: 'PromoDuration', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('PromoDuration') },
            { xtype: 'textfield', name: 'EventName', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('EventName') },
            { xtype: 'textfield', name: 'PromoStatusName', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('PromoStatusName') },
            {
                xtype: 'textfield',
                name: 'InOut',
                fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('InOut'),
                listeners: {
                    afterrender: function (value) {
                        this.setValue(value.rawValue === 'true' ? l10n.ns('core', 'booleanValues').value('true') : l10n.ns('core', 'booleanValues').value('false'));
                    }
                }
            },
            {
                xtype: 'textfield',
                name: 'IsGrowthAcceleration',
                fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('IsGrowthAcceleration'),
                listeners: {
                    afterrender: function (value) {
                        this.setValue(value.rawValue === 'true' ? l10n.ns('core', 'booleanValues').value('true') : l10n.ns('core', 'booleanValues').value('false'));
                    }
                }
            },
            {
                xtype: 'textfield',
                name: 'IsPriceIncrease',
                fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('IsPriceIncrease'),
                listeners: {
                    afterrender: function (value) {
                        this.setValue(value.rawValue === 'true' ? l10n.ns('core', 'booleanValues').value('true') : l10n.ns('core', 'booleanValues').value('false'));
                    }
                }
            },
            { xtype: 'textfield', name: 'PlanInstoreMechanicName', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('PlanInstoreMechanicName') },
            { xtype: 'textfield', name: 'PlanInstoreMechanicTypeName', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('PlanInstoreMechanicTypeName') },
            { xtype: 'numberfield', name: 'PlanInstoreMechanicDiscount', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('PlanInstoreMechanicDiscount') },
            { xtype: 'numberfield', name: 'PlanInStoreShelfPrice', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('PlanInStoreShelfPrice') },
            { xtype: 'numberfield', name: 'PCPrice', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('PCPrice') },
            { xtype: 'numberfield', name: 'PlanPromoBaselineVolume', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('PlanPromoBaselineVolume') },
            { xtype: 'numberfield', name: 'PlanPromoIncrementalVolume', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('PlanPromoIncrementalVolume') },
            { xtype: 'numberfield', name: 'PlanPromoNetIncrementalVolume', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('PlanPromoNetIncrementalVolume') },
            { xtype: 'numberfield', name: 'PlanPromoBaselineLSV', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('PlanPromoBaselineLSV') },
            { xtype: 'numberfield', name: 'PlanPromoIncrementalLSV', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('PlanPromoIncrementalLSV') },
            { xtype: 'numberfield', name: 'PlanPromoLSV', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('PlanPromoLSV') },
            { xtype: 'numberfield', name: 'PlanPromoUpliftPercent', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('PlanPromoUpliftPercent') },
            { xtype: 'numberfield', name: 'PlanPromoTIShopper', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('PlanPromoTIShopper') },
            { xtype: 'numberfield', name: 'PlanPromoTIMarketing', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('PlanPromoTIMarketing') },
            { xtype: 'numberfield', name: 'PlanPromoXSites', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('PlanPromoXSites') },
            { xtype: 'numberfield', name: 'PlanPromoCatalogue', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('PlanPromoCatalogue') },
            { xtype: 'numberfield', name: 'PlanPromoPOSMInClient', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('PlanPromoPOSMInClient') },
            { xtype: 'numberfield', name: 'PlanPromoBranding', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('PlanPromoBranding') },
            { xtype: 'numberfield', name: 'PlanPromoBTL', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('PlanPromoBTL') },
            { xtype: 'numberfield', name: 'PlanPromoCostProduction', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('PlanPromoCostProduction') },
            { xtype: 'numberfield', name: 'PlanPromoCostProdXSites', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('PlanPromoCostProdXSites') },
            { xtype: 'numberfield', name: 'PlanPromoCostProdCatalogue', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('PlanPromoCostProdCatalogue') },
            { xtype: 'numberfield', name: 'PlanPromoCostProdPOSMInClient', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('PlanPromoCostProdPOSMInClient') },
            { xtype: 'numberfield', name: 'PlanPromoCost', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('PlanPromoCost') },
            { xtype: 'numberfield', name: 'TIBasePercent', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('TIBasePercent') },
            { xtype: 'numberfield', name: 'PlanPromoIncrementalBaseTI', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('PlanPromoIncrementalBaseTI') },
            { xtype: 'numberfield', name: 'PlanPromoNetIncrementalBaseTI', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('PlanPromoNetIncrementalBaseTI') },
            { xtype: 'numberfield', name: 'COGSPercent', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('COGSPercent') },
            { xtype: 'numberfield', name: 'COGSTn', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('COGSTn') },
            { xtype: 'numberfield', name: 'PlanPromoIncrementalCOGS', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('PlanPromoIncrementalCOGS') },
            { xtype: 'numberfield', name: 'PlanPromoNetIncrementalCOGS', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('PlanPromoNetIncrementalCOGS') },
            { xtype: 'numberfield', name: 'PlanPromoIncrementalCOGSTn', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('PlanPromoIncrementalCOGSTn') },
            { xtype: 'numberfield', name: 'PlanPromoNetIncrementalCOGSTn', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('PlanPromoNetIncrementalCOGSTn') },
            { xtype: 'numberfield', name: 'PlanPromoTotalCost', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('PlanPromoTotalCost') },
            { xtype: 'numberfield', name: 'PlanPromoPostPromoEffectLSV', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('PlanPromoPostPromoEffectLSV') },
            { xtype: 'numberfield', name: 'PlanPromoNetIncrementalLSV', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('PlanPromoNetIncrementalLSV') },
            { xtype: 'numberfield', name: 'PlanPromoNetLSV', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('PlanPromoNetLSV') },
            { xtype: 'numberfield', name: 'PlanPromoBaselineBaseTI', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('PlanPromoBaselineBaseTI') },
            { xtype: 'numberfield', name: 'PlanPromoBaseTI', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('PlanPromoBaseTI') },
            { xtype: 'numberfield', name: 'PlanPromoNetBaseTI', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('PlanPromoNetBaseTI') },
            { xtype: 'numberfield', name: 'PlanPromoNSV', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('PlanPromoNSV') },
            { xtype: 'numberfield', name: 'PlanPromoNetNSV', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('PlanPromoNetNSV') },
            { xtype: 'numberfield', name: 'PlanPromoIncrementalNSV', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('PlanPromoIncrementalNSV') },
            { xtype: 'numberfield', name: 'PlanPromoNetIncrementalNSV', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('PlanPromoNetIncrementalNSV') },
            { xtype: 'numberfield', name: 'PlanPromoIncrementalMAC', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('PlanPromoIncrementalMAC') },
            { xtype: 'numberfield', name: 'PlanPromoNetIncrementalMAC', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('PlanPromoNetIncrementalMAC') },
            { xtype: 'numberfield', name: 'PlanPromoIncrementalEarnings', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('PlanPromoIncrementalEarnings') },
            { xtype: 'numberfield', name: 'PlanPromoNetIncrementalEarnings', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('PlanPromoNetIncrementalEarnings') },
            { xtype: 'numberfield', name: 'PlanPromoROIPercent', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('PlanPromoROIPercent') },
            { xtype: 'numberfield', name: 'PlanPromoNetROIPercent', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('PlanPromoNetROIPercent') },
            { xtype: 'numberfield', name: 'PlanPromoNetUpliftPercent', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('PlanPromoNetUpliftPercent') },
            { xtype: 'textfield', name: 'ActualInStoreMechanicName', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('ActualInStoreMechanicName') },
            { xtype: 'textfield', name: 'ActualInStoreMechanicTypeName', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('ActualInStoreMechanicTypeName') },
            { xtype: 'numberfield', name: 'ActualInStoreDiscount', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('ActualInStoreDiscount') },
            { xtype: 'numberfield', name: 'ActualInStoreShelfPrice', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('ActualInStoreShelfPrice') },
            { xtype: 'textfield', name: 'InvoiceNumber', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('InvoiceNumber') },
            { xtype: 'numberfield', name: 'ActualPromoVolume', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('ActualPromoVolume') },
            { xtype: 'numberfield', name: 'ActualPromoIncrementalVolume', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('ActualPromoIncrementalVolume') },
            { xtype: 'numberfield', name: 'ActualPromoNetIncrementalVolume', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('ActualPromoNetIncrementalVolume') },
            { xtype: 'numberfield', name: 'ActualPromoBaselineLSV', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('ActualPromoBaselineLSV') },
            { xtype: 'numberfield', name: 'ActualPromoIncrementalLSV', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('ActualPromoIncrementalLSV') },
            { xtype: 'numberfield', name: 'ActualPromoLSVByCompensation', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('ActualPromoLSVByCompensation') },
            { xtype: 'numberfield', name: 'ActualPromoLSV', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('ActualPromoLSV') },
            { xtype: 'numberfield', name: 'ActualPromoUpliftPercent', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('ActualPromoUpliftPercent') },
            { xtype: 'numberfield', name: 'ActualPromoNetUpliftPercent', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('ActualPromoNetUpliftPercent') },
            { xtype: 'numberfield', name: 'ActualPromoTIShopper', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('ActualPromoTIShopper') },
            { xtype: 'numberfield', name: 'ActualPromoTIMarketing', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('ActualPromoTIMarketing') },
            { xtype: 'numberfield', name: 'ActualPromoXSites', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('ActualPromoXSites') },
            { xtype: 'numberfield', name: 'ActualPromoCatalogue', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('ActualPromoCatalogue') },
            { xtype: 'numberfield', name: 'ActualPromoPOSMInClient', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('ActualPromoPOSMInClient') },
            { xtype: 'numberfield', name: 'ActualPromoBranding', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('ActualPromoBranding') },
            { xtype: 'numberfield', name: 'ActualPromoBTL', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('ActualPromoBTL') },
            { xtype: 'numberfield', name: 'ActualPromoCostProduction', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('ActualPromoCostProduction') },
            { xtype: 'numberfield', name: 'ActualPromoCostProdXSites', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('ActualPromoCostProdXSites') },
            { xtype: 'numberfield', name: 'ActualPromoCostProdCatalogue', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('ActualPromoCostProdCatalogue') },
            { xtype: 'numberfield', name: 'ActualPromoCostProdPOSMInClient', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('ActualPromoCostProdPOSMInClient') },
            { xtype: 'numberfield', name: 'ActualPromoCost', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('ActualPromoCost') },
            { xtype: 'numberfield', name: 'ActualPromoIncrementalBaseTI', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('ActualPromoIncrementalBaseTI') },
            { xtype: 'numberfield', name: 'ActualPromoNetIncrementalBaseTI', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('ActualPromoNetIncrementalBaseTI') },
            { xtype: 'numberfield', name: 'ActualPromoIncrementalCOGS', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('ActualPromoIncrementalCOGS') },
            { xtype: 'numberfield', name: 'ActualPromoNetIncrementalCOGS', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('ActualPromoNetIncrementalCOGS') },
            { xtype: 'numberfield', name: 'ActualPromoIncrementalCOGSTn', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('ActualPromoIncrementalCOGSTn') },
            { xtype: 'numberfield', name: 'ActualPromoNetIncrementalCOGSTn', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('ActualPromoNetIncrementalCOGSTn') },
            { xtype: 'numberfield', name: 'ActualPromoTotalCost', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('ActualPromoTotalCost') },
            { xtype: 'numberfield', name: 'ActualPromoPostPromoEffectLSV', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('ActualPromoPostPromoEffectLSV') },
            { xtype: 'numberfield', name: 'ActualPromoNetIncrementalLSV', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('ActualPromoNetIncrementalLSV') },
            { xtype: 'numberfield', name: 'ActualPromoNetLSV', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('ActualPromoNetLSV') },
            { xtype: 'numberfield', name: 'ActualPromoIncrementalNSV', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('ActualPromoIncrementalNSV') },
            { xtype: 'numberfield', name: 'ActualPromoNetIncrementalNSV', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('ActualPromoNetIncrementalNSV') },
            { xtype: 'numberfield', name: 'ActualPromoBaselineBaseTI', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('ActualPromoBaselineBaseTI') },
            { xtype: 'numberfield', name: 'ActualPromoBaseTI', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('ActualPromoBaseTI') },
            { xtype: 'numberfield', name: 'ActualPromoNetBaseTI', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('ActualPromoNetBaseTI') },
            { xtype: 'numberfield', name: 'ActualPromoNSV', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('ActualPromoNSV') },
            { xtype: 'numberfield', name: 'ActualPromoNetNSV', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('ActualPromoNetNSV') },
            { xtype: 'numberfield', name: 'ActualPromoIncrementalMAC', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('ActualPromoIncrementalMAC') },
            { xtype: 'numberfield', name: 'ActualPromoNetIncrementalMAC', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('ActualPromoNetIncrementalMAC') },
            { xtype: 'numberfield', name: 'ActualPromoIncrementalEarnings', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('ActualPromoIncrementalEarnings') },
            { xtype: 'numberfield', name: 'ActualPromoNetIncrementalEarnings', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('ActualPromoNetIncrementalEarnings') },
            { xtype: 'numberfield', name: 'ActualPromoROIPercent', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('ActualPromoROIPercent') },
            { xtype: 'numberfield', name: 'ActualPromoNetROIPercent', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('ActualPromoNetROIPercent') },
            { xtype: 'textfield', name: 'PromoTypesName', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('PromoTypesName') },
            { xtype: 'numberfield', name: 'SumInvoice', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('SumInvoice') },
            { xtype: 'numberfield', name: 'PlanPromoIncrementalMACLSV', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('PlanPromoIncrementalMACLSV') },
            { xtype: 'numberfield', name: 'PlanPromoNetIncrementalMACLSV', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('PlanPromoNetIncrementalMACLSV') },
            { xtype: 'numberfield', name: 'ActualPromoIncrementalMACLSV', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('ActualPromoIncrementalMACLSV') },
            { xtype: 'numberfield', name: 'ActualPromoNetIncrementalMACLSV', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('ActualPromoNetIncrementalMACLSV') },
            { xtype: 'numberfield', name: 'PlanPromoIncrementalEarningsLSV', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('PlanPromoIncrementalEarningsLSV') },
            { xtype: 'numberfield', name: 'PlanPromoNetIncrementalEarningsLSV', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('PlanPromoNetIncrementalEarningsLSV') },
            { xtype: 'numberfield', name: 'ActualPromoIncrementalEarningsLSV', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('ActualPromoIncrementalEarningsLSV') },
            { xtype: 'numberfield', name: 'ActualPromoNetIncrementalEarningsLSV', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('ActualPromoNetIncrementalEarningsLSV') },
            { xtype: 'numberfield', name: 'PlanPromoROIPercentLSV', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('PlanPromoROIPercentLSV') },
            { xtype: 'numberfield', name: 'PlanPromoNetROIPercentLSV', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('PlanPromoNetROIPercentLSV') },
            { xtype: 'numberfield', name: 'ActualPromoROIPercentLSV', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('ActualPromoROIPercentLSV') },
            { xtype: 'numberfield', name: 'ActualPromoNetROIPercentLSV', fieldLabel: l10n.ns('tpm', 'PromoPriceIncreaseROIReport').value('ActualPromoNetROIPercentLSV') },

        ]
    },

    buttons: [{
        text: l10n.ns('core', 'buttons').value('close'),
        itemId: 'close'
    }, {
        text: l10n.ns('core', 'buttons').value('cancel'),
        itemId: 'canceledit',
        hidden: true
    }, {
        text: l10n.ns('core', 'buttons').value('edit'),
        itemId: 'edit',
        hidden: true
    }, {
        text: l10n.ns('core', 'buttons').value('ok'),
        itemId: 'ok',
        hidden: true
    }]
});
