Ext.define('App.view.tpm.common.promoDashboardTpl', {

    formatTpl: new Ext.XTemplate([
    '<div id="promo-rowexpander-wrap" style="width: 990px; height: 100%;">',
        // Basic
        '<div class="promo-rowexpander-frame" style="padding: 0px 5px 0px 0px">',
            '<div class="custom-promo-panel" style="margin-left: 12px; width: 385px; height: 150px;">',
                '<table>',
                    '<tr>',
                        // Name + Status
                        '<td>',
                            '<b data-qtip="{[this.rowFormat(values.Name)]}" style="text-overflow: ellipsis; overflow: hidden; display: inline-block; max-width: 119px; white-space: nowrap;">{[this.rowFormat(values.Name)]}</b><b style="text-overflow: ellipsis; overflow: hidden; display: inline-block; white-space: nowrap; margin-left: 5px">(ID: {[values.Number]})</b></br>',
                            '<div class="border-left-box promo-grid-row" style="height: 18px; border-color: {[values.PromoStatusColor]};">',
                                '<span style="text-align: left;"><b>Status:</b> {[values.PromoStatusName]}</br>',
                            '</div>',
                        '</td>',
                        // Event
                        '<td>',
                            '<fieldset class="x-fieldset x-fieldset-with-title x-fieldset-with-legend" style="width: 160px; height: 44px; margin: 0">',
                                '<legend class="x-fieldset-header x-fieldset-header-default" id="fieldset-1110-legend" tabindex="-1"><span id="fieldset-1110-legend-outerCt" style="display: table;" role="presentation">',
                                '<div id="fieldset-1110-legend-innerCt" style="height: 100%; vertical-align: top; display: table-cell;" class="" role="presentation">',
                                '<div class="x-component x-fieldset-header-text x-component-default" id="fieldset-1110-legendTitle">Event</div></div></span></legend>',
                                '<div class="x-fieldset-body x-box-layout-ct" style="padding-left: 3px; width: 150px; font-size: 13px">',
                                    '{[this.rowFormat(values.PromoEventName)]}',
                                '</div>',
                            '</fieldset>',
                        '</td>',
                    '</tr>',
                    '<tr>',
                        // Client
                        '<td>',
                            '<fieldset class="x-fieldset x-fieldset-with-title x-fieldset-with-legend" style="width: 190px; height: 43px; margin: 0">',
								'<legend class="x-fieldset-header x-fieldset-header-default" id="fieldset-1110-legend" tabindex="-1"><span id="fieldset-1110-legend-outerCt" style="display: table;" role="presentation">',
                                '<div id="fieldset-1110-legend-innerCt" style="height: 100%; vertical-align: top; display: table-cell;" class="" role="presentation">',
                                '<div class="x-component x-fieldset-header-text x-component-default" id="fieldset-1110-legendTitle">Client</div></div></span></legend>',
                                '<div class="x-fieldset-body promo-fieldset x-box-layout-ct" style="padding-left: 3px; width: 180px; font-size: 11px">',
									'<span data-qtip="{[this.tipFormat(values.ClientHierarchy)]}">',
                                        '{[this.rowFormat(values.ClientHierarchy)]}',
                                    '</span>',
                                '</div>',
                            '</fieldset>',
                        '</td>',
                        // Duration Date
                        '<td>',
                            '<fieldset class="x-fieldset x-fieldset-with-title x-fieldset-with-legend" style="width: 160px; height: 43px; margin: 0">',
                                '<legend class="x-fieldset-header x-fieldset-header-default" id="fieldset-1110-legend" tabindex="-1"><span id="fieldset-1110-legend-outerCt" style="display: table;" role="presentation">',
                                '<div id="fieldset-1110-legend-innerCt" style="height: 100%; vertical-align: top; display: table-cell;" class="" role="presentation">',
                                '<div class="x-component x-fieldset-header-text x-component-default" id="fieldset-1110-legendTitle">Duration date</div></div></span></legend>',
                                '<div class="x-fieldset-body x-box-layout-ct" style="padding-left: 3px; width: 150px; font-size: 13px">',
                                    '{[this.formatDate(values.StartDate)]} - {[this.formatDate(values.EndDate)]}',
                                '</div>',
                            '</fieldset>',
                        '</td>',
                    '</tr>',
                    '<tr>',
                        // Product
                        '<td>',
                            '<fieldset class="x-fieldset x-fieldset-with-title x-fieldset-with-legend" style="width: 190px; height: 43px; margin: -1px 0 0 0">',
                                '<legend class="x-fieldset-header x-fieldset-header-default" id="fieldset-1110-legend" tabindex="-1"><span id="fieldset-1110-legend-outerCt" style="display: table;" role="presentation">',
                                '<div id="fieldset-1110-legend-innerCt" style="height: 100%; vertical-align: top; display: table-cell;" class="" role="presentation">',
                                '<div class="x-component x-fieldset-header-text x-component-default" id="fieldset-1110-legendTitle">Product</div></div></span></legend>',
                                '<div class="x-fieldset-body promo-fieldset x-box-layout-ct" style="padding-left: 3px; width: 180px; font-size: 11px">',
                                    '<span data-qtip="{[this.tipFormat(values.ProductHierarchy)]}">',
                                        '{[this.rowFormat(values.ProductHierarchy)]}',
                                    '</span>',
                                '</div>',
                            '</fieldset>',
                        '</td>',
                        // Dispatch date
                        '<td>',
                            '<fieldset class="x-fieldset x-fieldset-with-title x-fieldset-with-legend" style="width: 160px; height: 43px; margin: -1px 0 0 0">',
                                '<legend class="x-fieldset-header x-fieldset-header-default" id="fieldset-1110-legend" tabindex="-1"><span id="fieldset-1110-legend-outerCt" style="display: table;" role="presentation">',
                                '<div id="fieldset-1110-legend-innerCt" style="height: 100%; vertical-align: top; display: table-cell;" class="" role="presentation">',
                                '<div class="x-component x-fieldset-header-text x-component-default" id="fieldset-1110-legendTitle">Dispatch date</div></div></span></legend>',
                                '<div class="x-fieldset-body x-box-layout-ct" style="padding-left: 3px; width: 150px; font-size: 13px">',
                                    '{[this.formatDate(values.DispatchesStart)]} - {[this.formatDate(values.DispatchesEnd)]}',
                                '</div>',
                            '</fieldset>',
                        '</td>',
                    '</tr>',
                '</table>',
            '</div>',
        '</div>',
        // Financial plan
        '<div class="promo-rowexpander-frame" style="{[this.isDisplayPlan(values.PromoStatusName)]} padding: 0px 5px 0px 0px">',
            '<div class="custom-promo-panel" style="margin: 0px; width: 290px; height: 150px;">',
                '<fieldset class="x-fieldset x-fieldset-with-title x-fieldset-with-legend" style="margin: 0px; width: 260px; height: 140px;">',
                    '<legend class="x-fieldset-header x-fieldset-header-default" id="fieldset-1110-legend" tabindex="-1"><span id="fieldset-1110-legend-outerCt" style="display: table;" role="presentation">',
                    '<div id="fieldset-1110-legend-innerCt" style="height: 100%; vertical-align: top; display: table-cell;" class="" role="presentation">',
                    '<div class="x-component x-fieldset-header-text x-component-default" id="fieldset-1110-legendTitle">Financial plan</div></div></span></legend>',
                    '<div class="x-fieldset-body x-box-layout-ct" style="padding-left: 3px; width: 250px;">',
                        '<div class="x-box-inner" role="presentation" style="height: 120px; width: 250px;">',
                            '<div class="x-box-target" role="presentation" style="width: 240px;">',
                                '<table class="x-field x-table-plain x-form-item x-form-readonly x-form-type-text x-box-item x-field-default x-vbox-form-item" style="width: 245px; left: 0px;">',
                                    '<tbody>',
                                        // PlanPromoNetIncrementalNSV
                                        '<tr role="presentation" id="singlelinedisplayfield-1111-inputRow" class="x-form-item-input-row">',
		                                    '<td role="presentation" id="singlelinedisplayfield-1111-labelCell" style="width: 140px" valign="top" halign="left" width="105" class="x-field-label-cell">',
			                                '<label id="singlelinedisplayfield-1111-labelEl" for="singlelinedisplayfield-1111-inputEl" class="x-form-item-label x-unselectable singleline-lable x-form-item-label-left" style="width: 150px!important; margin-right: 5px; font-size: 13px" unselectable="on">',
                                                'Total promo NSV, MRUR</label></td>',
			                                '<td role="presentation" class="x-form-item-body x-form-display-field-body" style="width: 65px!important; position: static;">',
			                                    '<div id="singlelinedisplayfield-1111-inputEl" role="textbox" class="x-form-display-field singlelinedisplayfield" data-errorqtip="" style="width: suto; font-size: 13px">',
                                                    '{[this.millionFormat(values.PlanPromoNetIncrementalNSV)]}',
                                                '</div>',
                                            '</td>',
                                        '<tr><td></td></tr>',
                                        // PlanPromoIncrementalNSV
                                        '<tr role="presentation" id="singlelinedisplayfield-1111-inputRow" class="x-form-item-input-row">',
		                                    '<td role="presentation" id="singlelinedisplayfield-1111-labelCell" style="width: 140px" valign="top" halign="left" width="105" class="x-field-label-cell">',
			                                '<label id="singlelinedisplayfield-1111-labelEl" for="singlelinedisplayfield-1111-inputEl" class="x-form-item-label x-unselectable singleline-lable x-form-item-label-left" style="width: 150px!important; margin-right: 5px; font-size: 13px" unselectable="on">',
                                                'Incremental NSV, MRUR</label></td>',
			                                '<td role="presentation" class="x-form-item-body x-form-display-field-body" style="width: 65px!important; position: static;">',
			                                    '<div id="singlelinedisplayfield-1111-inputEl" role="textbox" class="x-form-display-field singlelinedisplayfield" data-errorqtip="" style="width: auto; font-size: 13px">',
                                                    '{[this.millionFormat(values.PlanPromoIncrementalNSV)]}',
                                                '</div>',
                                            '</td>',
                                        '</tr>',
                                        '<tr><td></td></tr>',
                                        // PlanPromoUpliftPercent
                                        '<tr role="presentation" id="singlelinedisplayfield-1111-inputRow" class="x-form-item-input-row">',
		                                    '<td role="presentation" id="singlelinedisplayfield-1111-labelCell" style="width: 140px" valign="top" halign="left" width="105" class="x-field-label-cell">',
			                                '<label id="singlelinedisplayfield-1111-labelEl" for="singlelinedisplayfield-1111-inputEl" class="x-form-item-label x-unselectable singleline-lable x-form-item-label-left" style="width: 150px!important; margin-right: 5px; font-size: 13px" unselectable="on">',
                                                'Uplift, %</label></td>',
			                                '<td role="presentation" class="x-form-item-body x-form-display-field-body" style="width: 65px!important; position: static;">',
			                                    '<div id="singlelinedisplayfield-1111-inputEl" role="textbox" class="x-form-display-field singlelinedisplayfield" data-errorqtip="" style="width: auto; font-size: 13px">',
                                                    '{[this.simpleFormat(values.PlanPromoUpliftPercent)]}',
                                                '</div>',
                                            '</td>',
                                        '</tr>',
                                        '<tr><td></td></tr>',
                                        // PlanPromoROIPercent
                                        '<tr role="presentation" id="singlelinedisplayfield-1111-inputRow" class="x-form-item-input-row">',
		                                    '<td role="presentation" id="singlelinedisplayfield-1111-labelCell" style="width: 140px" valign="top" halign="left" width="105" class="x-field-label-cell">',
			                                '<label id="singlelinedisplayfield-1111-labelEl" for="singlelinedisplayfield-1111-inputEl" class="x-form-item-label x-unselectable singleline-lable x-form-item-label-left" style="width: 150px!important; margin-right: 5px; font-size: 13px" unselectable="on">',
                                                'ROI, %</label></td>',
			                                '<td role="presentation" class="x-form-item-body x-form-display-field-body" style="width: 65px!important; position: static;">',
			                                    '<div id="singlelinedisplayfield-1111-inputEl" role="textbox" class="x-form-display-field singlelinedisplayfield" data-errorqtip="" style="width: auto; font-size: 13px">',
                                                    '{[this.simpleFormat(values.PlanPromoROIPercent)]}',
                                                '</div>',
                                            '</td>',
                                        '</tr>',
                                    '</tbody>',
                                '</table>',
                            '</div>',
                        '</div>',
                    '</div>',
                '</fieldset>',
            '</div>',
        '</div>',
        // Support plan
        '<div class="promo-rowexpander-frame" style="{[this.isDisplayPlan(values.PromoStatusName)]} padding: 0px 5px 0px 0px">',
            '<div class="custom-promo-panel" style="margin: 0px; width: 280px; height: 150px;">',
                '<fieldset class="x-fieldset x-fieldset-with-title x-fieldset-with-legend" style="margin: 0px; width: 250px; height: 140px; border: 0;">',
                    '<legend class="x-fieldset-header x-fieldset-header-default" id="fieldset-1110-legend" tabindex="-1"><span id="fieldset-1110-legend-outerCt" style="display: table;" role="presentation">',
                    '<div id="fieldset-1110-legend-innerCt" style="height: 100%; vertical-align: top; display: table-cell;" class="" role="presentation">',
                    '<div class="x-component x-fieldset-header-text x-component-default" id="fieldset-1110-legendTitle">Support plan</div></div></span></legend>',
                    '<div class="x-fieldset-body x-box-layout-ct" style="padding-left: 3px; width: 240px;">',
                        '<div class="x-box-inner" role="presentation" style="height: 120px; width: 240px;">',
                            '<div class="x-box-target" role="presentation" style="width: 240px;">',
                                '<table class="x-field x-table-plain x-form-item x-form-readonly x-form-type-text x-box-item x-field-default x-vbox-form-item" style="width: 235px; left: 0px;">',
                                    '<tbody>',
                                        // PlanPromoTIShopper
                                        '<tr role="presentation" id="singlelinedisplayfield-1111-inputRow" class="x-form-item-input-row">',
		                                    '<td role="presentation" id="singlelinedisplayfield-1111-labelCell" style="width: 130px" valign="top" halign="left" width="105" class="x-field-label-cell">',
			                                '<label id="singlelinedisplayfield-1111-labelEl" for="singlelinedisplayfield-1111-inputEl" class="x-form-item-label x-unselectable singleline-lable x-form-item-label-left" style="width: 140px!important; margin-right: 5px; font-size: 13px" unselectable="on">',
                                                'Shopper Ti, MRUR</label></td>',
			                                '<td role="presentation" class="x-form-item-body x-form-display-field-body" style="width: 65px!important; position: static;">',
			                                    '<div id="singlelinedisplayfield-1111-inputEl" role="textbox" class="x-form-display-field singlelinedisplayfield" data-errorqtip="" style="width: auto; font-size: 13px">',
                                                    '{[this.millionFormat(values.PlanPromoTIShopper)]}',
                                                '</div>',
                                            '</td>',
                                        '<tr><td></td></tr>',
                                        // PlanPromoTIMarketing
                                        '<tr role="presentation" id="singlelinedisplayfield-1111-inputRow" class="x-form-item-input-row">',
		                                    '<td role="presentation" id="singlelinedisplayfield-1111-labelCell" style="width: 130px" valign="top" halign="left" width="105" class="x-field-label-cell">',
			                                '<label id="singlelinedisplayfield-1111-labelEl" for="singlelinedisplayfield-1111-inputEl" class="x-form-item-label x-unselectable singleline-lable x-form-item-label-left" style="width: 140px!important; margin-right: 5px; font-size: 13px" unselectable="on">',
                                                'Marketing Ti, MRUR</label></td>',
			                                '<td role="presentation" class="x-form-item-body x-form-display-field-body" style="width: 65px!important; position: static;">',
			                                    '<div id="singlelinedisplayfield-1111-inputEl" role="textbox" class="x-form-display-field singlelinedisplayfield" data-errorqtip="" style="width: auto; font-size: 13px">',
                                                    '{[this.millionFormat(values.PlanPromoTIMarketing)]}',
                                                '</div>',
                                            '</td>',
                                        '</tr>',
                                        '<tr style="height: 20px;"><td></td></tr>',
                                        // PromoCostsTypes
                                        '<td id="PromoCostsTypesPlan" colspan="2">',
                                            '<div style="display: inline-block; padding: 0px 15px 0px 0px">',
                                                '<div class="border-left-box promo-grid-row" style="border-color: {[this.isEmptyValueColor(values.PlanPromoXSites)]};">',
                                                    '<span style="text-align:left;"><b>X-Sites</b></br> {[this.isEmptyValue(values.PlanPromoXSites)]}</br>',
                                                '</div>',
                                            '</div>',
                                            '<div style="display: inline-block; padding: 0px 15px 0px 0px">',
                                                '<div class="border-left-box promo-grid-row" style="border-color: {[this.isEmptyValueColor(values.PlanPromoCatalogue)]};">',
                                                    '<span style="text-align:left;"><b>Catalog</b></br> {[this.isEmptyValue(values.PlanPromoCatalogue)]}</br>',
                                                '</div>',
                                            '</div>',
                                            '<div style="display: inline-block;">',
                                                '<div class="border-left-box promo-grid-row" style="border-color: {[this.isEmptyValueColor(values.PlanPromoPOSMInClient)]};">',
                                                    '<span style="text-align:left;"><b>POSM</b></br> {[this.isEmptyValue(values.PlanPromoPOSMInClient)]}</br>',
                                                '</div>',
                                            '</div>',
                                        '</td>',
                                    '</tbody>',
                                '</table>',
                            '</div>',
                        '</div>',
                    '</div>',
                '</fieldset>',
            '</div>',
            '<div style="float: right; margin-top: -45px; margin-right: -25px; display: {[values.IsGrowthAcceleration ? \'inline\' : \'none\']};">',
                '<img src="/Bundles/style/images/GA.png"/>',
            '</div>',
        '</div>',
        // Financial fact
        '<div class="promo-rowexpander-frame" style="{[this.isDisplayFact(values.PromoStatusName)]} padding: 0px 5px 0px 0px">',
            '<div class="custom-promo-panel" style="margin: 0px; width: 280px; height: 150px;">',
                '<fieldset class="x-fieldset x-fieldset-with-title x-fieldset-with-legend" style="margin: 0px; width: 250px; height: 140px;">',
                    '<legend class="x-fieldset-header x-fieldset-header-default" id="fieldset-1110-legend" tabindex="-1"><span id="fieldset-1110-legend-outerCt" style="display:table;" role="presentation">',
                    '<div id="fieldset-1110-legend-innerCt" style="height: 100%; vertical-align: top; display: table-cell;" class="" role="presentation">',
                    '<div class="x-component x-fieldset-header-text x-component-default" id="fieldset-1110-legendTitle">Financial fact</div></div></span></legend>',
                    '<div class="x-fieldset-body x-box-layout-ct" style="padding-left: 3px; width: 250px;">',
                        '<div class="x-box-inner" role="presentation" style="height: 120px; width: 250px;">',
                            '<div class="x-box-target" role="presentation" style="width: 250px;">',
                                '<table class="x-field x-table-plain x-form-item x-form-readonly x-form-type-text x-box-item x-field-default x-vbox-form-item" style="width: 245px; left: 0px;">',
                                    '<tbody>',
                                        // ActualPromoNetIncrementalNSV
                                        '<tr role="presentation" id="singlelinedisplayfield-1111-inputRow" class="x-form-item-input-row">',
		                                    '<td role="presentation" id="singlelinedisplayfield-1111-labelCell" style="width: 140px" valign="top" halign="left" width="105" class="x-field-label-cell">',
			                                '<label id="singlelinedisplayfield-1111-labelEl" for="singlelinedisplayfield-1111-inputEl" class="x-form-item-label x-unselectable singleline-lable x-form-item-label-left" style="width: 150px!important; margin-right: 5px; font-size: 13px" unselectable="on">',
                                                'Total promo NSV, MRUR</label></td>',
			                                '<td role="presentation" class="x-form-item-body x-form-display-field-body" style="width: 65px!important;">',
			                                    '<div id="singlelinedisplayfield-1111-inputEl" role="textbox" class="x-form-display-field singlelinedisplayfield" data-errorqtip="" style="width: auto; font-size: 13px">',
                                                    '{[this.millionFormat(values.PActualPromoNetIncrementalNSV)]}',
                                                '</div>',
                                            '</td>',
                                        '<tr><td></td></tr>',
                                        // ActualPromoIncrementalNSV
                                        '<tr role="presentation" id="singlelinedisplayfield-1111-inputRow" class="x-form-item-input-row">',
		                                    '<td role="presentation" id="singlelinedisplayfield-1111-labelCell" style="width: 130px" valign="top" halign="left" width="105" class="x-field-label-cell">',
			                                '<label id="singlelinedisplayfield-1111-labelEl" for="singlelinedisplayfield-1111-inputEl" class="x-form-item-label x-unselectable singleline-lable x-form-item-label-left" style="width: 150px!important; margin-right: 5px; font-size: 13px" unselectable="on">',
                                                'Incremental NSV, MRUR</label></td>',
			                                '<td role="presentation" class="x-form-item-body x-form-display-field-body" style="width: 65px!important;">',
			                                    '<div id="singlelinedisplayfield-1111-inputEl" role="textbox" class="x-form-display-field singlelinedisplayfield" data-errorqtip="" style="width: auto; font-size: 13px">',
                                                    '{[this.millionFormat(values.ActualPromoIncrementalNSV)]}',
                                                '</div>',
                                            '</td>',
                                        '</tr>',
                                        '<tr><td></td></tr>',
                                        // ActualPromoUpliftPercent
                                        '<tr role="presentation" id="singlelinedisplayfield-1111-inputRow" class="x-form-item-input-row">',
		                                    '<td role="presentation" id="singlelinedisplayfield-1111-labelCell" style="width: 130px" valign="top" halign="left" width="105" class="x-field-label-cell">',
			                                '<label id="singlelinedisplayfield-1111-labelEl" for="singlelinedisplayfield-1111-inputEl" class="x-form-item-label x-unselectable singleline-lable x-form-item-label-left" style="width: 150px!important; margin-right: 5px; font-size: 13px" unselectable="on">',
                                                'Uplift, %</label></td>',
			                                '<td role="presentation" class="x-form-item-body x-form-display-field-body" style="width: 65px!important;">',
			                                    '<div id="singlelinedisplayfield-1111-inputEl" role="textbox" class="x-form-display-field singlelinedisplayfield" data-errorqtip="" style="width: auto; font-size: 13px">',
                                                    '{[this.simpleFormat(values.ActualPromoUpliftPercent)]}',
                                                '</div>',
                                            '</td>',
                                        '</tr>',
                                        '<tr><td></td></tr>',
                                        // ActualPromoROIPercent
                                        '<tr role="presentation" id="singlelinedisplayfield-1111-inputRow" class="x-form-item-input-row">',
		                                    '<td role="presentation" id="singlelinedisplayfield-1111-labelCell" style="width: 130px" valign="top" halign="left" width="105" class="x-field-label-cell">',
			                                '<label id="singlelinedisplayfield-1111-labelEl" for="singlelinedisplayfield-1111-inputEl" class="x-form-item-label x-unselectable singleline-lable x-form-item-label-left" style="width: 150px!important; margin-right: 5px; font-size: 13px" unselectable="on">',
                                                'ROI, %</label></td>',
			                                '<td role="presentation" class="x-form-item-body x-form-display-field-body" style="width: 65px!important;">',
			                                    '<div id="singlelinedisplayfield-1111-inputEl" role="textbox" class="x-form-display-field singlelinedisplayfield" data-errorqtip="" style="width: auto; font-size: 13px">',
                                                    '{[this.simpleFormat(values.ActualPromoROIPercent)]}',
                                                '</div>',
                                            '</td>',
                                        '</tr>',
                                    '</tbody>',
                                '</table>',
                            '</div>',
                        '</div>',
                    '</div>',
                '</fieldset>',
            '</div>',
        '</div>',
        // Support fact
        '<div class="promo-rowexpander-frame" style="{[this.isDisplayFact(values.PromoStatusName)]} padding: 0px 5px 0px 0px">',
            '<div class="custom-promo-panel" style="margin: 0px; width: 270px; height: 150px;">',
                '<fieldset class="x-fieldset x-fieldset-with-title x-fieldset-with-legend" style="margin: 0px; width: 240px; height: 140px;">',
                    '<legend class="x-fieldset-header x-fieldset-header-default" id="fieldset-1110-legend" tabindex="-1"><span id="fieldset-1110-legend-outerCt" style="display:table;" role="presentation">',
                    '<div id="fieldset-1110-legend-innerCt" style="height: 100%; vertical-align: top; display: table-cell;" class="" role="presentation">',
                    '<div class="x-component x-fieldset-header-text x-component-default" id="fieldset-1110-legendTitle">Support fact</div></div></span></legend>',
                    '<div class="x-fieldset-body x-box-layout-ct" style="padding-left: 3px; width: 240px;">',
                        '<div class="x-box-inner" role="presentation" style="height: 120px; width: 240px;">',
                            '<div class="x-box-target" role="presentation" style="width: 240px;">',
                                '<table class="x-field x-table-plain x-form-item x-form-readonly x-form-type-text x-box-item x-field-default x-vbox-form-item" style="width: 235px; left: 0px;">',
                                    '<tbody>',
                                        // ActualPromoTIShopper
                                        '<tr role="presentation" id="singlelinedisplayfield-1111-inputRow" class="x-form-item-input-row">',
		                                    '<td role="presentation" id="singlelinedisplayfield-1111-labelCell" style="width: 130px" valign="top" halign="left" width="105" class="x-field-label-cell">',
			                                '<label id="singlelinedisplayfield-1111-labelEl" for="singlelinedisplayfield-1111-inputEl" class="x-form-item-label x-unselectable singleline-lable x-form-item-label-left" style="width:140px!important; margin-right:5px; font-size: 13px" unselectable="on">',
                                                'Shopper Ti, MRUR</label></td>',
			                                '<td role="presentation" class="x-form-item-body x-form-display-field-body" style="width: 65px!important;">',
			                                    '<div id="singlelinedisplayfield-1111-inputEl" role="textbox" class="x-form-display-field singlelinedisplayfield" data-errorqtip="" style="width: auto; font-size: 13px">',
                                                    '{[this.millionFormat(values.ActualPromoTIShopper)]}',
                                                '</div>',
                                            '</td>',
                                        '<tr><td></td></tr>',
                                        // ActualPromoTIMarketing
                                        '<tr role="presentation" id="singlelinedisplayfield-1111-inputRow" class="x-form-item-input-row">',
		                                    '<td role="presentation" id="singlelinedisplayfield-1111-labelCell" style="width: 130px" valign="top" halign="left" width="105" class="x-field-label-cell">',
			                                '<label id="singlelinedisplayfield-1111-labelEl" for="singlelinedisplayfield-1111-inputEl" class="x-form-item-label x-unselectable singleline-lable x-form-item-label-left" style="width:140px!important; margin-right:5px; font-size: 13px" unselectable="on">',
                                                'Marketing Ti, MRUR</label></td>',
			                                '<td role="presentation" class="x-form-item-body x-form-display-field-body" style="width: 65px!important;">',
			                                    '<div id="singlelinedisplayfield-1111-inputEl" role="textbox" class="x-form-display-field singlelinedisplayfield" data-errorqtip="" style="width: auto; font-size: 13px">',
                                                    '{[this.millionFormat(values.ActualPromoTIMarketing)]}',
                                                '</div>',
                                            '</td>',
                                        '</tr>',
                                        '<tr style="height: 20px;"><td></td></tr>',
                                        // PromoCostsTypes
                                        '<td id="PromoCostsTypesFact" colspan="2">',
                                            '<div style="display: inline-block; padding: 0px 15px 0px 0px">',
                                                '<div class="border-left-box promo-grid-row" style="border-color: {[this.isEmptyValueColor(values.ActualPromoXSites)]};">',
                                                    '<span style="text-align:left;"><b>X-Sites</b></br> {[this.isEmptyValue(values.ActualPromoXSites)]}</br>',
                                                '</div>',
                                            '</div>',
                                            '<div style="display: inline-block; padding: 0px 15px 0px 0px">',
                                                '<div class="border-left-box promo-grid-row" style="border-color: {[this.isEmptyValueColor(values.ActualPromoCatalogue)]};">',
                                                    '<span style="text-align:left;"><b>Catalog</b></br> {[this.isEmptyValue(values.ActualPromoCatalogue)]}</br>',
                                                '</div>',
                                            '</div>',
                                            '<div style="display: inline-block;">',
                                                '<div class="border-left-box promo-grid-row" style="border-color: {[this.isEmptyValueColor(values.ActualPromoPOSMInClient)]};">',
                                                    '<span style="text-align:left;"><b>POSM</b></br> {[this.isEmptyValue(values.ActualPromoPOSMInClient)]}</br>',
                                                '</div>',
                                            '</div>',
                                        '</td>',
                                    '</tbody>',
                                '</table>',
                            '</div>',
                        '</div>',
                    '</div>',
                '</fieldset>',
            '</div>',
        '</div>',
    '</div>',
    {
        formatDate: function (value) {
            return Ext.util.Format.date(value, 'd.m.Y');
        },
        rowFormat: function (value) {
            if (value) {
                return renderWithDelimiter(value, ' > ', '  ');
            }
            else {
                return '-';
            }     
		},
		tipFormat: function (value) {
			return value;
		},
        simpleFormat: function (value) {
            return value ? Ext.util.Format.number(value, '0.00') : '-';
        },
        millionFormat: function (value) {
            var result = '-';            

            if (value !== null && value !== undefined) {
                var valueToDisplay = null;

                if (this.blockBillion) {
                    valueToDisplay = value;
                }
                else {
                    this.originValue = value;
                    valueToDisplay = value / 1000000.0;
                }

                result = Ext.util.Format.number(valueToDisplay, '0.00');
            }

            return result;
        },
        isDisplayPlan: function (value) {
            return value == 'Closed' ? 'display: none;' : '';
        },
        isDisplayFact: function (value) {
            return value == 'Closed' ? '' : 'display: none;';
        },
        isEmptyValueColor: function (value) {
            return value !== null && value !== undefined ? '#4CAF50' : '#F44336';
        },
        isEmptyValue: function (value) {
            return value !== null && value !== undefined ? 'Yes' : 'No';
		}
    }
    ])
});