Ext.define('App.model.tpm.promo.HistoricalPromo', {
    extend: 'Ext.data.Model',
    idProperty: '_Id',
    breezeEntityType: 'Promo',
    fields: [
        { name: '_Id', type: 'string', hidden: true },
        { name: '_ObjectId', hidden: true },
        { name: '_User', type: 'string', isDefault: true },
        { name: '_Role', type: 'string', isDefault: true },
        { name: '_EditDate', type: 'date', isDefault: true },
        { name: '_Operation', type: 'string', isDefault: true },
        { name: 'BrandId', useNull: true, hidden: true, isDefault: true },
        { name: 'BrandTechId', useNull: true, hidden: true, isDefault: true },
        { name: 'PromoStatusId', useNull: true, hidden: true, isDefault: true },
        { name: 'MechanicId', useNull: true, hidden: true, isDefault: true },
        { name: 'MechanicTypeId', useNull: true, hidden: true, isDefault: true },
        { name: 'CreatorId', useNull: true, hidden: true, isDefault: true },
        { name: 'ClientTreeId', useNull: true, hidden: true, isDefault: true },
        //{ name: 'BaseClientTreeId', useNull: true, hidden: true, isDefault: true },
        { name: 'BaseClientTreeIds', useNull: true, hidden: true, isDefault: true },
        { name: 'ColorId', useNull: true, hidden: true, isDefault: true },
        { name: 'Number', type: 'int', hidden: false, isDefault: true },
        { name: 'ClientHierarchy', type: 'string', hidden: false, isDefault: true },
        { name: 'ProductHierarchy', type: 'string', hidden: false, isDefault: true },
        { name: 'Name', type: 'string', hidden: false, isDefault: true },
        { name: 'StartDate', useNull: true, type: 'date', hidden: false, isDefault: true },
        { name: 'EndDate', useNull: true, type: 'date', hidden: false, isDefault: true },
        { name: 'DispatchesStart', useNull: true, type: 'date', hidden: false, isDefault: true },
        { name: 'DispatchesEnd', useNull: true, type: 'date', hidden: false, isDefault: true },
        { name: 'EventName', useNull: true, type: 'string', hidden: false, isDefault: true },
        { name: 'CalendarPriority', useNull: true, type: 'int', hidden: false, isDefault: true },
        { name: 'BrandName', type: 'string' },
        { name: 'BrandTechName', type: 'string' },
        { name: 'MechanicComment', type: 'string', hidden: false, isDefault: true },
        { name: 'PromoStatusName', type: 'string' },
        { name: 'PromoStatusSystemName', type: 'string' },
        { name: 'Mechanic', type: 'string' },
        { name: 'MarsMechanicName', type: 'string' },
        { name: 'MarsMechanicTypeName', type: 'string' },
        { name: 'MechanicIA', type: 'string' },
        { name: 'PlanInstoreMechanicName', type: 'string' },
        { name: 'PlanInstoreMechanicTypeName', type: 'string' },
        { name: 'MarsMechanicDiscount', type: 'int' },
        { name: 'PlanInstoreMechanicDiscount', type: 'int' },
        { name: 'ColorSystemName', type: 'string' },
        { name: 'ColorDisplayName', type: 'string' },
        { name: 'PromoDuration', useNull: true, type: 'int', hidden: false, isDefault: false },
        { name: 'DispatchDuration', useNull: true, type: 'int', hidden: false, isDefault: false },
        { name: 'InvoiceNumber', type: 'string', hidden: false, isDefault: false },

        // Calculation
        { name: 'PlanPromoTIShopper', useNull: true, type: 'int', hidden: false, isDefault: false },
        { name: 'PlanPromoTIMarketing', useNull: true, type: 'int', hidden: false, isDefault: false },
        { name: 'PlanPromoBranding', useNull: true, type: 'int', hidden: false, isDefault: false },
        { name: 'PlanPromoCost', useNull: true, type: 'int', hidden: false, isDefault: false },
        { name: 'PlanPromoBTL', useNull: true, type: 'int', hidden: false, isDefault: false },
        { name: 'PlanPromoCostProduction', useNull: true, type: 'float', hidden: false, isDefault: false },
        { name: 'PlanPromoUpliftPercent', useNull: true, type: 'float', hidden: false, isDefault: false },
        { name: 'PlanPromoIncrementalLSV', useNull: true, type: 'int', hidden: false, isDefault: false },
        { name: 'PlanPromoIncrementalLSV', useNull: true, type: 'int', hidden: false, isDefault: false },
        { name: 'PlanPostPromoEffect', useNull: true, type: 'int', hidden: false, isDefault: false },
        { name: 'PlanPromoROIPercent', useNull: true, type: 'int', hidden: false, isDefault: false },
        { name: 'PlanPromoIncrementalNSV', useNull: true, type: 'int', hidden: false, isDefault: false },
        { name: 'PlanPromoNetIncrementalNSV', useNull: true, type: 'int', hidden: false, isDefault: false },
        { name: 'PlanPromoIncrementalMAC', useNull: true, type: 'int', hidden: false, isDefault: false },
        { name: 'NeedRecountUplift', type: 'bool', hidden: true, isDefault: false, defaultValue: true },
        { name: 'PlanPromoXSites', useNull: true, type: 'float', hidden: false, isDefault: false },
        { name: 'PlanPromoCatalogue', useNull: true, type: 'float', hidden: false, isDefault: false },
        { name: 'PlanPromoPOSMInClient', useNull: true, type: 'float', hidden: false, isDefault: false },
        { name: 'PlanPromoCostProdXSites', useNull: true, type: 'float', hidden: false, isDefault: false },
        { name: 'PlanPromoCostProdCatalogue', useNull: true, type: 'float', hidden: false, isDefault: false },
        { name: 'PlanPromoCostProdPOSMInClient', useNull: true, type: 'float', hidden: false, isDefault: false },
        { name: 'ActualPromoXSites', useNull: true, type: 'float', hidden: false, isDefault: false },
        { name: 'ActualPromoCatalogue', useNull: true, type: 'float', hidden: false, isDefault: false },
        { name: 'ActualPromoPOSMInClient', useNull: true, type: 'float', hidden: false, isDefault: false },
        { name: 'ActualPromoCostProdXSites', useNull: true, type: 'float', hidden: false, isDefault: false },
        { name: 'ActualPromoCostProdCatalogue', useNull: true, type: 'float', hidden: false, isDefault: false },
        { name: 'ActualPromoCostProdPOSMInClient', useNull: true, type: 'float', hidden: false, isDefault: false },
        { name: 'PlanPromoBaselineLSV', useNull: true, type: 'float', hidden: false, isDefault: false },
        { name: 'PlanPromoIncrementalBaseTI', useNull: true, type: 'float', hidden: false, isDefault: false },
        { name: 'PlanPromoIncrementalCOGS', useNull: true, type: 'float', hidden: false, isDefault: false },
        { name: 'PlanPromoTotalCost', useNull: true, type: 'float', hidden: false, isDefault: false },
        { name: 'PlanPromoNetIncrementalLSV', useNull: true, type: 'float', hidden: false, isDefault: false },
        { name: 'PlanPromoNetLSV', useNull: true, type: 'float', hidden: false, isDefault: false },
        { name: 'PlanPromoNetIncrementalMAC', useNull: true, type: 'float', hidden: false, isDefault: false },
        { name: 'PlanPromoIncrementalEarnings', useNull: true, type: 'float', hidden: false, isDefault: false },
        { name: 'PlanPromoNetIncrementalEarnings', useNull: true, type: 'float', hidden: false, isDefault: false },
        { name: 'PlanPromoROIPercent', useNull: true, type: 'int', hidden: false, isDefault: false },
        { name: 'PlanPromoNetUpliftPercent', useNull: true, type: 'int', hidden: false, isDefault: false },
        { name: 'ActualPromoBaselineLSV', useNull: true, type: 'float', hidden: false, isDefault: false },
        { name: 'ActualInStoreDiscount', useNull: true, type: 'int', hidden: false, isDefault: false },
        { name: 'ActualInStoreShelfPrice', useNull: true, type: 'float', hidden: false, isDefault: false },
        { name: 'ActualPromoIncrementalBaseTI', useNull: true, type: 'float', hidden: false, isDefault: false },
        { name: 'ActualPromoIncrementalCOGS', useNull: true, type: 'float', hidden: false, isDefault: false },
        { name: 'ActualPromoTotalCost', useNull: true, type: 'float', hidden: false, isDefault: false },
        { name: 'ActualPromoNetIncrementalLSV', useNull: true, type: 'float', hidden: false, isDefault: false },
        { name: 'ActualPromoNetLSV', useNull: true, type: 'float', hidden: false, isDefault: false },
        { name: 'ActualPromoNetIncrementalMAC', useNull: true, type: 'float', hidden: false, isDefault: false },
        { name: 'ActualPromoIncrementalEarnings', useNull: true, type: 'float', hidden: false, isDefault: false },
        { name: 'ActualPromoNetIncrementalEarnings', useNull: true, type: 'float', hidden: false, isDefault: false },
        { name: 'ActualPromoNetROIPercent', useNull: true, type: 'int', hidden: false, isDefault: false },
        { name: 'ActualPromoNetUpliftPercent', useNull: true, type: 'int', hidden: false, isDefault: false },
        { name: 'PlanPromoBaselineBaseTI', useNull: true, type: 'float', hidden: false, isDefault: false },
        { name: 'PlanPromoBaseTI', useNull: true, type: 'float', hidden: false, isDefault: false },
        { name: 'PlanPromoNetNSV', useNull: true, type: 'float', hidden: false, isDefault: false },
        { name: 'ActualPromoBaselineBaseTI', useNull: true, type: 'float', hidden: false, isDefault: false },
        { name: 'ActualPromoBaseTI', useNull: true, type: 'float', hidden: false, isDefault: false },
        { name: 'ActualPromoNetNSV', useNull: true, type: 'float', hidden: false, isDefault: false },

        // Promo Closure
        { name: 'ActualPromoTIShopper', useNull: true, type: 'float', hidden: false, isDefault: false },
        { name: 'ActualPromoTIMarketing', useNull: true, type: 'float', hidden: false, isDefault: false },
        { name: 'ActualPromoBranding', useNull: true, type: 'float', hidden: false, isDefault: false },
        { name: 'ActualPromoBTL', useNull: true, type: 'float', hidden: false, isDefault: false },
        { name: 'ActualPromoCostProduction', useNull: true, type: 'float', hidden: false, isDefault: false },
        { name: 'ActualPromoCost', useNull: true, type: 'float', hidden: false, isDefault: false },
        { name: 'ActualPromoUpliftPercent', useNull: true, type: 'float', hidden: false, isDefault: false },
        { name: 'ActualPromoIncrementalLSV', useNull: true, type: 'float', hidden: false, isDefault: false },
        { name: 'ActualPromoLSV', useNull: true, type: 'float', hidden: false, isDefault: false },
        { name: 'FactPostPromoEffect', useNull: true, type: 'int', hidden: false, isDefault: false },
        { name: 'ActualPromoROIPercent', useNull: true, type: 'int', hidden: false, isDefault: false },
        { name: 'ActualPromoIncrementalNSV', useNull: true, type: 'float', hidden: false, isDefault: false },
        { name: 'ActualPromoNetIncrementalNSV', useNull: true, type: 'float', hidden: false, isDefault: false },
        { name: 'ActualPromoIncrementalMAC', useNull: true, type: 'float', hidden: false, isDefault: false },
        
        //MarsDates
        { name: 'MarsStartDate', type: 'string', hidden: false, isDefault: false },
        { name: 'MarsEndDate', type: 'string', hidden: false, isDefault: false },
        { name: 'MarsDispatchesStart', type: 'string', hidden: false, isDefault: false },
        { name: 'MarsDispatchesEnd', type: 'string', hidden: false, isDefault: false },

       //Дата последнего вхождения в статус Approved
        { name: 'LastApprovedDate', type: 'date', hidden: true, isDefault: true },


        { name: 'IsAutomaticallyApproved', type: 'bool', hidden: false, isDefault: false },
        { name: 'IsCustomerMarketingApproved', type: 'bool', hidden: false, isDefault: false },
        { name: 'IsDemandPlanningApproved', type: 'bool', hidden: false, isDefault: false },
        { name: 'IsDemandFinanceApproved', type: 'bool', hidden: false, isDefault: false },
        { name: 'OtherEventName', type: 'string', hidden: false, isDefault: false },
        { name: 'PlanPromoLSV', type: 'float', hidden: false, isDefault: false },
        { name: 'PlanPostPromoEffectW1', type: 'float', hidden: false, isDefault: false },
        { name: 'PlanPostPromoEffectW2', type: 'float', hidden: false, isDefault: false },
        { name: 'FactPostPromoEffectW1', type: 'float', hidden: false, isDefault: false },
        { name: 'FactPostPromoEffectW2', type: 'float', hidden: false, isDefault: false },
        { name: 'ActualInStoreMechanicDiscount', type: 'float', hidden: false, isDefault: false },
        { name: 'PromoStatusColor', type: 'string', hidden: false, isDefault: false },
        { name: 'RejectReasonName', type: 'string', hidden: false, isDefault: false },
        { name: 'ActualInStoreMechanicName', type: 'string', hidden: false, isDefault: false },
        { name: 'ActualInStoreMechanicTypeName', type: 'string', hidden: false, isDefault: false },
        { name: 'ProductTreeObjectIds', type: 'string', hidden: false, isDefault: false },


    ],
    proxy: {
        type: 'breeze',
        resourceName: 'HistoricalPromoes',
        reader: {
            type: 'json',
            totalProperty: 'inlineCount',
            root: 'results'
        }
    }
});
