using Core.ModuleRegistrator;

using Looper.Core;

using System.Collections.Generic;

namespace Module.Host.TPM
{
    public class HostTPMModuleRegistrator : IHostModuleRegistrator {
        public IEnumerable<IHandler> GetHandlers() {
            return new List<IHandler>()
            {
                new Handlers.Notifications.PromoDemandChangeNotificationHandler(),
                new Handlers.Notifications.PromoProductChangeNotificationHandler(),
                new Handlers.Notifications.PromoUpliftFailNotificationHandler(),
                new Handlers.Notifications.CancelledPromoNotificationHandler(),
                new Handlers.Notifications.WeekBeforeDispatchPromoNotificationHandler(),
                new Handlers.Notifications.PromoOnApprovalNotificationHandler(),
                new Handlers.Notifications.PromoOnRejectNotificationHandler(),
                new Handlers.Notifications.PromoApprovedNotificationHandler(),
                new Handlers.Notifications.PromoROIReportNotificationHandler(),
                new Handlers.Notifications.ProductSyncFailNotificationHandler(),
                new Handlers.FullXLSXUpdateImportPromoSalesHandler(),
                new Handlers.FullXLSXUpdateImportDemandHandler(),
                new Handlers.FullXLSXUpdateImportClientShareHandler(),
                new Handlers.FullXLSXCOGSUpdateImportHandler(),
                new Handlers.FullXLSXTradeInvestmentUpdateImportHandler(),
                new Handlers.FullXLSXRATIShopperUpdateImportHandler(),
                new Handlers.FullXLSXImportBaseLineHandler(),
                new Handlers.FullXLSXUpdateImportIncrementalPromoHandler(),
                new Handlers.UpdateUpliftHandler(),
                new Handlers.CalculatePromoParametersHandler(),
                new Handlers.CalculateBudgetsHandler(),
                new Handlers.CalculateBTLBudgetsHandler(),
                new Handlers.CalculateActualParamatersHandler(),
                new Handlers.PromoWorkflowHandler(),
                new Handlers.FullXLSXImportPromoProductHandler(),
                new Handlers.FullXLSXImportPromoProductPluHandler(),
                new Handlers.FullXLSXImportPromoProductFromTLCHandler(),
                new Handlers.BaseLineUpgradeHandler(),
                new Handlers.SchedulerExportHandler(),
                new Handlers.FullXLSXImportNonPromoDMPHandler(),
                new Handlers.FullXLSXImportPromoDMPHandler(),
                new Handlers.FullXLSXUpdateBrandTechHandler(),
                new Handlers.FullXLSXUpdateAllHandler(),
                new Handlers.FullXLSXUpdateBudgetSubItemHandler(),
                new Handlers.FullXLSXUpdateNonPromoEquipmentHandler(),
                new Handlers.FullXLSXNoNegoUpdateImporHandler(),
                new Handlers.FullXLSXMechanicTypeUpdateImporHandler(),
                new Handlers.FullXLSXAssortmentMatrixImportHandler(),
                new Handlers.FullXLSXCompetitorBrandTechUpdateImportHandler(),
                new Handlers.FullXLSXCompetitorPromoUpdateImportHandler(),
                new Handlers.FullXLSXCompetitorPromoUpdateNewImportHandler(),
                new Handlers.FullXLSXCompetitorUpdateImportHandler(),
                new Handlers.FullXLSXPLUDictionaryImportHandler(),
                new Handlers.AutoResetPromoHandler(),
                new Handlers.XLSXImportActualLsvHandler(),
                new Handlers.ActualLSVChangeHandler(),
                new Handlers.DataFlow.RecalculateAllPromoesHandler(),
                new Handlers.DataFlow.DataFlowFilteringHandler(),
                new Handlers.DataFlow.DataFlowRecalculatingHandler(),
                new Handlers.PromoPartialWorkflowHandler(),
                new Handlers.RemoveDeletedDataHandler(),
                new Handlers.FillInOutProductIdsHandler(),
                new Handlers.DataLakeIntegrationHandlers.MarsCustomersCheckHandler(),
                new Handlers.Notifications.ClientTreeNeedUpdateNotificationHandler(),
                new Handlers.UnblockPromoesHandler(),
                new Handlers.FullXLSXUpdateImportPromoProductsCorrectionHandler(),
                new Handlers.FullXLSXUpdateImportPromoProductsUpliftHandler(),
                new Handlers.PromoListPlanRecalculationHandler(),
                new Handlers.PromoListActualRecalculationHandler(),
                new Handlers.DataLakeIntegrationHandlers.MarsProductsCheckStarterHandler(),
                new Handlers.DataLakeIntegrationHandlers.MarsProductsCheckHandler(),
                new Handlers.SetTIBasePercentValuesHandler(),
                new Handlers.SetCOGSPercentValuesHandler(),
                new Handlers.PriceListMergeHandler(),
                new Handlers.Interface.Incoming.InputBaseLineProcessHandler(),
                new Handlers.StartSISOBaselineCalculationHandler(),
                new Handlers.FullXLSXUpdateCoefficientSI2SOHandler(),
                new Handlers.SellOutBaselineQtyCalculationHandler(),
                new Handlers.NightProcessingMainHandler(),
                new Handlers.Interface.Outcoming.OutputIncrementalProcessHandler(),
                new Handlers.DayIncrementalQTYRecalculationHandler(),
                new Handlers.CreateCoefficientSI2SOHandler(),
                new Handlers.FullXLSXUpdateImportClientDashboardHandler(),
                new Handlers.FullXLSXUpdateImportRollingVolumesHandler(),
                new Handlers.RollingVolumeQTYRecalculationHandler(),
                new Handlers.FullXLSXUpdateTechnologyHandler(),
                new Handlers.RestartMainNightProcessingHandler(),
                new Handlers.NightProcessingWaitHandler(),
                new Handlers.ReapprovingHandler(),
                new Handlers.ExportHandler(),
                new Handlers.MassApproveHandler(),
                new Handlers.SendingFilesToBlobHandler(),
                new Handlers.FullXLSXRPAEventImportHandler(),
                new Handlers.FullXLSXRPAPromoSupportImportHandler(),
                new Handlers.FullXLSXRPANonPromoSupportImportHandler(),
                new Handlers.FullXLSXRPAActualEANPCImportHandler(),
                new Handlers.FullXLSXRpaActualPluImportHandler()
            };
        }
    }
}