apiVersion: v1
kind: PersistentVolumeClaim
metadata: 
  name: {{ .Values.name }}
  namespace: airflow
spec:
  accessModes:
  - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: "csi-s3"