---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: airlow-dags-source
spec:
  storageClassName: csi-s3
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  claimRef:
    namespace: airflow
    name: dags-s3-pvc-static
  csi:
    driver: ru.yandex.s3.csi
    volumeHandle: yac-sb-yac-dp-0000520221201171956288700000002/airflow/dags
    controllerPublishSecretRef:
      name: csi-s3-secret
      namespace: kube-system
    nodePublishSecretRef:
      name: csi-s3-secret
      namespace: kube-system
    nodeStageSecretRef:
      name: csi-s3-secret
      namespace: kube-system
    volumeAttributes:
      capacity: 10Gi
      mounter: geesefs
      options: "--memory-limit 1000 --dir-mode 0777 --file-mode 0666 --uid 1001"
