---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: dags-s3-pvc-static
  namespace: airflow
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
  storageClassName: ""
