IF NOT EXISTS (SELECT * FROM SYSOBJECTS WHERE NAME = N'CurrentDayIncremental')
CREATE TABLE CurrentDayIncremental (
	Id UNIQUEIDENTIFIER PRIMARY KEY,
	WEEK NVARCHAR(12),
	PromoId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Promo(Id),
	ProductId UNIQUEIDENTIFIER FOREIGN KEY REFERENCES Product(Id),
	IncrementalQty FLOAT,
	LastChangeDate DATETIMEOFFSET(7),
	DemandCode NVARCHAR(255),
	DMDGroup NVARCHAR(MAX)
)
GO