CREATE OR ALTER 
	TRIGGER [dbo].[BTL_Increment_Number] ON [dbo].[BTL] AFTER INSERT AS BEGIN UPDATE BTL SET Number = (SELECT ISNULL((SELECT MAX(Number) FROM BTL), 0) + 1) FROM Inserted WHERE BTL.Id = Inserted.Id; END
GO