INSERT INTO [Promo] ([Id], [Disabled], [DeletedDate], [BrandId], [TechnologyId], [PromoStatusId], [Name], [StartDate], [EndDate], [PlanUplift], [FactUplift], [MarsMechanicId], [InstoreMechanicId], [MarsMechanicDiscount], [InstoreMechanicDiscount], [ClientHierarchy], [ProductHierarchy], [ClientTreeId], [ProductTreeId])
VALUES (NEWID(), 0 ,NULL, (SELECT TOP 1 Id FROM Brand WHERE Name = 'Kitekat'), (SELECT TOP 1 Id FROM Technology WHERE Name = 'Pouch'), (SELECT TOP 1 Id FROM PromoStatus WHERE SystemName = 'Closed'), 'TestUpliftPromo_01', '2017-06-17 00:00:00.0000000 +03:00', '2017-07-17 00:00:00.0000000 +03:00', 105, 95, (SELECT TOP 1 Id FROM Mechanic WHERE SystemName = 'TPR'), (SELECT TOP 1 Id FROM Mechanic WHERE SystemName = 'TPR'), 24, 24, 'NA > X5 Retail Group', 'Kitekat > Pouch', (SELECT TOP 1 ObjectId FROM ClientTree WHERE Name = 'X5 Retail Group'), (SELECT TOP 1 ObjectId FROM ProductTree WHERE FullPathName = 'Kitekat > Pouch' AND EndDate IS NULL))

INSERT INTO [Promo] ([Id], [Disabled], [DeletedDate], [BrandId], [TechnologyId], [PromoStatusId], [Name], [StartDate], [EndDate], [PlanUplift], [FactUplift], [MarsMechanicId], [InstoreMechanicId], [MarsMechanicDiscount], [InstoreMechanicDiscount], [ClientHierarchy], [ProductHierarchy], [ClientTreeId], [ProductTreeId])
VALUES (NEWID(), 0 ,NULL, (SELECT TOP 1 Id FROM Brand WHERE Name = 'Kitekat'), (SELECT TOP 1 Id FROM Technology WHERE Name = 'Pouch'), (SELECT TOP 1 Id FROM PromoStatus WHERE SystemName = 'Closed'), 'TestUpliftPromo_02', '2017-06-17 00:00:00.0000000 +03:00', '2017-07-17 00:00:00.0000000 +03:00', 95, 85, (SELECT TOP 1 Id FROM Mechanic WHERE SystemName = 'TPR'), (SELECT TOP 1 Id FROM Mechanic WHERE SystemName = 'TPR'), 24, 24, 'NA > X5 Retail Group', 'Kitekat > Pouch', (SELECT TOP 1 ObjectId FROM ClientTree WHERE Name = 'X5 Retail Group'), (SELECT TOP 1 ObjectId FROM ProductTree WHERE FullPathName = 'Kitekat > Pouch' AND EndDate IS NULL))

INSERT INTO [Promo] ([Id], [Disabled], [DeletedDate], [BrandId], [TechnologyId], [PromoStatusId], [Name], [StartDate], [EndDate], [PlanUplift], [FactUplift], [MarsMechanicId], [InstoreMechanicId], [MarsMechanicDiscount], [InstoreMechanicDiscount], [ClientHierarchy], [ProductHierarchy], [ClientTreeId], [ProductTreeId])
VALUES (NEWID(), 0 ,NULL, (SELECT TOP 1 Id FROM Brand WHERE Name = 'Kitekat'), (SELECT TOP 1 Id FROM Technology WHERE Name = 'Pouch'), (SELECT TOP 1 Id FROM PromoStatus WHERE SystemName = 'Closed'), 'TestUpliftPromo_03', '2017-06-17 00:00:00.0000000 +03:00', '2017-07-17 00:00:00.0000000 +03:00', 85, 75, (SELECT TOP 1 Id FROM Mechanic WHERE SystemName = 'TPR'), (SELECT TOP 1 Id FROM Mechanic WHERE SystemName = 'TPR'), 24, 24, 'NA > X5 Retail Group', 'Kitekat > Pouch', (SELECT TOP 1 ObjectId FROM ClientTree WHERE Name = 'X5 Retail Group'), (SELECT TOP 1 ObjectId FROM ProductTree WHERE FullPathName = 'Kitekat > Pouch' AND EndDate IS NULL))

INSERT INTO [Promo] ([Id], [Disabled], [DeletedDate], [BrandId], [TechnologyId], [PromoStatusId], [Name], [StartDate], [EndDate], [PlanUplift], [FactUplift], [MarsMechanicId], [InstoreMechanicId], [MarsMechanicDiscount], [InstoreMechanicDiscount], [ClientHierarchy], [ProductHierarchy], [ClientTreeId], [ProductTreeId])
VALUES (NEWID(), 0 ,NULL, (SELECT TOP 1 Id FROM Brand WHERE Name = 'Sheba'), (SELECT TOP 1 Id FROM Technology WHERE Name = 'Pouch'), (SELECT TOP 1 Id FROM PromoStatus WHERE SystemName = 'Closed'), 'TestUpliftPromo_04', '2017-06-17 00:00:00.0000000 +03:00', '2017-12-31 00:00:00.0000000 +03:00', 75, 65, (SELECT TOP 1 Id FROM Mechanic WHERE SystemName = 'VP'), (SELECT TOP 1 Id FROM Mechanic WHERE SystemName = 'VP'), 4, 4, 'NA > X5 Retail Group', 'Sheba > Pouch > Pleasure', (SELECT TOP 1 ObjectId FROM ClientTree WHERE Name = 'X5 Retail Group'), (SELECT TOP 1 ObjectId FROM ProductTree WHERE FullPathName = 'Sheba > Pouch > Pleasure' AND EndDate IS NULL))

INSERT INTO [Promo] ([Id], [Disabled], [DeletedDate], [BrandId], [TechnologyId], [PromoStatusId], [Name], [StartDate], [EndDate], [PlanUplift], [FactUplift], [MarsMechanicId], [InstoreMechanicId], [MarsMechanicDiscount], [InstoreMechanicDiscount], [ClientHierarchy], [ProductHierarchy], [ClientTreeId], [ProductTreeId])
VALUES (NEWID(), 0 ,NULL, (SELECT TOP 1 Id FROM Brand WHERE Name = 'Sheba'), (SELECT TOP 1 Id FROM Technology WHERE Name = 'Pouch'), (SELECT TOP 1 Id FROM PromoStatus WHERE SystemName = 'Closed'), 'TestUpliftPromo_05', '2017-06-17 00:00:00.0000000 +03:00', '2017-12-31 00:00:00.0000000 +03:00', 65, 55, (SELECT TOP 1 Id FROM Mechanic WHERE SystemName = 'VP'), (SELECT TOP 1 Id FROM Mechanic WHERE SystemName = 'VP'), 4, 4, 'NA > X5 Retail Group', 'Sheba > Pouch > Pleasure', (SELECT TOP 1 ObjectId FROM ClientTree WHERE Name = 'X5 Retail Group'), (SELECT TOP 1 ObjectId FROM ProductTree WHERE FullPathName = 'Sheba > Pouch > Pleasure' AND EndDate IS NULL))

GO